# Generated by Django 6.0.2 on 2026-02-04 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('age', models.CharField(max_length=10, verbose_name='Yosh')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkak'), ('female', 'Ayol'), ('other', 'Boshqa')], max_length=10, verbose_name='Jins')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('complaints', models.TextField(verbose_name='Shikoyatlar')),
                ('history', models.TextField(blank=True, verbose_name='Anamnez')),
                ('objective_data', models.TextField(blank=True, verbose_name="Ob'ektiv ma'lumotlar")),
                ('lab_results', models.TextField(blank=True, verbose_name='Laboratoriya natijalari')),
                ('allergies', models.CharField(blank=True, max_length=500, verbose_name='Allergiyalar')),
                ('current_medications', models.TextField(blank=True, verbose_name='Hozirgi dori-darmonlar')),
                ('family_history', models.TextField(blank=True, verbose_name='Oilaviy anamnez')),
                ('additional_info', models.TextField(blank=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('structured_lab_results', models.JSONField(blank=True, default=dict, verbose_name='Struktur laboratoriya natijalari')),
                ('pharmacogenomics_report', models.TextField(blank=True, verbose_name='Farmakogenomika hisoboti')),
                ('symptom_timeline', models.JSONField(blank=True, default=list, verbose_name='Simptomlar vaqti')),
                ('mental_health_scores', models.JSONField(blank=True, default=dict, verbose_name='Ruhiy salomatlik skorlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='patient_attachments/%Y/%m/%d/', verbose_name='Fayl')),
                ('name', models.CharField(max_length=255, verbose_name='Fayl nomi')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME turi')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='patients.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Bemor fayli',
                'verbose_name_plural': 'Bemor fayllari',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name', 'last_name'], name='patients_pa_first_n_a142c0_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='patients_pa_created_542792_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_by'], name='patients_pa_created_15c993_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_by', 'created_at'], name='patients_pa_created_1db0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'),
        ),
    ]
