# Generated by Django 5.2.14 on 2026-06-06 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_patient_registry_fields'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='district_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Tuman ID'),
        ),
        migrations.AddField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Otasining ismi'),
        ),
        migrations.AddField(
            model_name='patient',
            name='home_clinic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='accounts.clinicgroup', verbose_name="Ro'yxatdan o'tgan klinika guruhi"),
        ),
        migrations.AddField(
            model_name='patient',
            name='region_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Viloyat ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, verbose_name="Manzil (qo'shimcha)"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='complaints',
            field=models.TextField(blank=True, default='', verbose_name='Shikoyatlar'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['region_id', 'district_id'], name='patients_pa_region__eeb3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['home_clinic_group'], name='patients_pa_home_cl_908a58_idx'),
        ),
    ]
