# Generated by Django 5.2.14 on 2026-06-29 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_primary_care_210'),
        ('patients', '0005_populationrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=500)),
                ('icd10_code', models.CharField(blank=True, max_length=20)),
                ('registered_date', models.DateField()),
                ('health_improvement_plan', models.TextField(blank=True)),
                ('form30_data', models.JSONField(blank=True, default=dict)),
                ('visit_frequency', models.CharField(blank=True, help_text='Masalan: oyiga 1 marta', max_length=100)),
                ('next_visit_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dispanser nazorati',
                'verbose_name_plural': 'Dispanser nazorati',
                'ordering': ['-registered_date'],
            },
        ),
        migrations.CreateModel(
            name='FamilyPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('address', models.TextField(blank=True)),
                ('region_id', models.CharField(blank=True, db_index=True, max_length=10)),
                ('district_id', models.CharField(blank=True, db_index=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oila pasporti',
                'verbose_name_plural': 'Oila pasportlari',
                'ordering': ['passport_number'],
            },
        ),
        migrations.CreateModel(
            name='FamilyPassportMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('head', 'Boshliq'), ('spouse', "Turmush o'rtog'i"), ('child', 'Farzand'), ('parent', 'Ota-ona'), ('other', 'Boshqa')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Oila a'zosi",
                'verbose_name_plural': "Oila a'zolari",
            },
        ),
        migrations.CreateModel(
            name='MedicalBrigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Brigada nomi')),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('region_id', models.CharField(blank=True, db_index=True, max_length=10)),
                ('district_id', models.CharField(blank=True, db_index=True, max_length=10)),
                ('target_population_size', models.PositiveIntegerField(default=3000)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tibbiyot brigadasi',
                'verbose_name_plural': 'Tibbiyot brigadalari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_level', models.CharField(choices=[('annual', 'Yillik tarmoq rejasi'), ('monthly', 'Oylik reja'), ('weekly', 'Haftalik reja')], default='annual', max_length=10)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('week_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('targets', models.JSONField(blank=True, default=dict, help_text="Reja ko'rsatkichlari")),
                ('completed', models.JSONField(blank=True, default=dict, help_text='Bajarilgan')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarmoq rejasi',
                'verbose_name_plural': 'Tarmoq rejalari',
                'ordering': ['-year', '-month', '-week_number'],
            },
        ),
        migrations.CreateModel(
            name='PatronageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(db_index=True)),
                ('visit_type', models.CharField(choices=[('universal_progressive', 'Universal-progressiv patronaj'), ('routine', 'Rejadagi patronaj'), ('high_risk', 'Yuqori xavf guruhi'), ('home_hospital', 'Uy shifoxonasi')], default='routine', max_length=30)),
                ('purpose', models.TextField(blank=True)),
                ('findings', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Patronaj tashrifi',
                'verbose_name_plural': 'Patronaj tashriflari',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveCheckup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkup_type', models.CharField(choices=[('preventive', "Profilaktik ko'rik"), ('in_depth', "Chuqurlashtirilgan ko'rik"), ('targeted', "Maqsadli ko'rik"), ('dispensary', "Dispanser ko'rik")], default='preventive', max_length=20)),
                ('checkup_date', models.DateField(db_index=True)),
                ('health_group', models.CharField(blank=True, choices=[('1', 'I — Tayanch'), ('2', 'II — Past xavf'), ('3', "III — O'rta xavf"), ('4', 'IV — Yuqori xavf'), ('child_1', 'Bola I'), ('child_2', 'Bola II'), ('child_3', 'Bola III')], max_length=10)),
                ('location', models.CharField(choices=[('clinic', 'Poliklinika'), ('home', 'Uyda'), ('school', 'Maktab/MTT')], default='clinic', max_length=20)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('risk_factors', models.JSONField(blank=True, default=dict)),
                ('new_diagnoses', models.TextField(blank=True)),
                ('existing_diagnoses', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('tactics', models.TextField(blank=True)),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Profilaktik ko'rik",
                'verbose_name_plural': "Profilaktik ko'riklar",
                'ordering': ['-checkup_date'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Rejada'), ('invited', 'Taklif qilingan'), ('completed', 'Bajarilgan'), ('excluded', 'Chiqarilgan')], default='planned', max_length=20)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('exclude_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Skrining ro'yxati",
                'verbose_name_plural': "Skrining ro'yxatlari",
                'ordering': ['-planned_date'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_gender', models.CharField(blank=True, help_text="male/female yoki bo'sh", max_length=10)),
                ('age_min', models.PositiveSmallIntegerField(default=0)),
                ('age_max', models.PositiveSmallIntegerField(default=120)),
                ('frequency_months', models.PositiveSmallIntegerField(default=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skrining dasturi',
                'verbose_name_plural': 'Skrining dasturlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_date', models.DateField()),
                ('result_status', models.CharField(choices=[('negative', 'Salbiy'), ('suspected', 'Shubha'), ('positive', 'Ijobiy')], default='negative', max_length=20)),
                ('lab_data', models.JSONField(blank=True, default=dict)),
                ('referral_specialist', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skrining natijasi',
                'verbose_name_plural': 'Skrining natijalari',
            },
        ),
        migrations.RenameIndex(
            model_name='populationrecord',
            new_name='patients_po_last_na_59ab57_idx',
            old_name='patients_po_last_na_idx',
        ),
        migrations.RenameIndex(
            model_name='populationrecord',
            new_name='patients_po_phone_efbc04_idx',
            old_name='patients_po_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='populationrecord',
            new_name='patients_po_region__4ddb72_idx',
            old_name='patients_po_region_idx',
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='dispensary_registered',
            field=models.BooleanField(default=False, verbose_name='Dispanser nazoratida'),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='health_group',
            field=models.CharField(blank=True, max_length=10, verbose_name="Sog'liq guruhi"),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='last_checkup_date',
            field=models.DateField(blank=True, null=True, verbose_name="Oxirgi ko'rik sanasi"),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='next_checkup_date',
            field=models.DateField(blank=True, null=True, verbose_name="Keyingi ko'rik sanasi"),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='risk_chronic',
            field=models.BooleanField(default=False, verbose_name='Surunkali kasallik'),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='risk_disabled',
            field=models.BooleanField(default=False, verbose_name='Nogironligi bor'),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='risk_lone_elderly',
            field=models.BooleanField(default=False, verbose_name="Yolg'iz keksa"),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='risk_needs_care',
            field=models.BooleanField(default=False, verbose_name='Parvarishga muhtoj'),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='risk_pregnant',
            field=models.BooleanField(default=False, verbose_name='Homilador'),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='risk_social_vulnerable',
            field=models.BooleanField(default=False, verbose_name='Ijtimoiy himoyaga muhtoj'),
        ),
        migrations.AddField(
            model_name='dispensaryrecord',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensary_records', to='patients.populationrecord'),
        ),
        migrations.AddField(
            model_name='dispensaryrecord',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_dispensary', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familypassport',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_families', to='patients.populationrecord'),
        ),
        migrations.AddField(
            model_name='familypassportmember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='patients.familypassport'),
        ),
        migrations.AddField(
            model_name='familypassportmember',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='patients.populationrecord'),
        ),
        migrations.AddField(
            model_name='medicalbrigade',
            name='clinic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_brigades', to='accounts.clinicgroup'),
        ),
        migrations.AddField(
            model_name='medicalbrigade',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_brigades', to=settings.AUTH_USER_MODEL, verbose_name='Oilaviy shifokor'),
        ),
        migrations.AddField(
            model_name='dispensaryrecord',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.medicalbrigade'),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_population', to='patients.medicalbrigade', verbose_name='Tibbiyot brigadasi'),
        ),
        migrations.AddField(
            model_name='networkplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_network_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkplan',
            name='brigade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_plans', to='patients.medicalbrigade'),
        ),
        migrations.AddField(
            model_name='patronagevisit',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patronage_visits', to='patients.medicalbrigade'),
        ),
        migrations.AddField(
            model_name='patronagevisit',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patronage_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patronagevisit',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patronage_visits', to='patients.populationrecord'),
        ),
        migrations.AddField(
            model_name='preventivecheckup',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkups', to='patients.medicalbrigade'),
        ),
        migrations.AddField(
            model_name='preventivecheckup',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_checkups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preventivecheckup',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='patients.populationrecord'),
        ),
        migrations.AddField(
            model_name='screeningenrollment',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.medicalbrigade'),
        ),
        migrations.AddField(
            model_name='screeningenrollment',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_enrollments', to='patients.populationrecord'),
        ),
        migrations.AddField(
            model_name='screeningenrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='patients.screeningprogram'),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='patients.screeningenrollment'),
        ),
        migrations.AddField(
            model_name='screeningresult',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='familypassportmember',
            unique_together={('family', 'population')},
        ),
        migrations.AddIndex(
            model_name='preventivecheckup',
            index=models.Index(fields=['checkup_date', 'health_group'], name='patients_pr_checkup_c95eda_idx'),
        ),
        migrations.AddIndex(
            model_name='preventivecheckup',
            index=models.Index(fields=['population', 'checkup_date'], name='patients_pr_populat_8e22c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='screeningenrollment',
            unique_together={('population', 'program')},
        ),
    ]
