# Generated by Django 5.2.14 on 2026-08-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_primary_care_210'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationrecord',
            name='disability_group',
            field=models.CharField(blank=True, choices=[('', "Nogironligi yo'q"), ('1', 'I guruh'), ('2', 'II guruh'), ('3', 'III guruh'), ('child', 'Bolalikdan nogiron')], db_index=True, max_length=10, verbose_name='Nogironlik guruhi'),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='dispensary_diagnosis',
            field=models.CharField(blank=True, max_length=255, verbose_name='D hisob tashxisi'),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='dispensary_icd_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='D hisob (NKB) kodi'),
        ),
        migrations.AddField(
            model_name='populationrecord',
            name='medical_card_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Tibbiy karta raqami'),
        ),
    ]
