# Generated by Django 5.2.14 on 2026-09-03 04:07

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_populationrecord_disability_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientattachment',
            name='file',
            field=models.FileField(upload_to=patients.models.patient_attachment_path, verbose_name='Fayl'),
        ),
    ]
