# Generated by Django 6.0.2 on 2026-02-04 19:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Reja nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('plan_type', models.CharField(choices=[('clinic', 'Klinika (shartnoma)'), ('doctor', 'Shifokor (chek)')], default='doctor', max_length=20, verbose_name='Obuna turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oylik narx')),
                ('price_currency', models.CharField(default='USD', max_length=10, verbose_name='Valyuta')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Obuna davri (kun)', verbose_name='Davr (kun)')),
                ('features', models.JSONField(blank=True, default=list, help_text='Imkoniyatlar ro\'yxati, masalan: ["Cheksiz tahlil", "AI Chat"]', verbose_name='Imkoniyatlar')),
                ('is_trial', models.BooleanField(default=False, verbose_name='Trial reja')),
                ('trial_days', models.PositiveIntegerField(default=0, verbose_name='Trial kun')),
                ('max_analyses_per_month', models.PositiveIntegerField(blank=True, help_text='Null = cheksiz', null=True, verbose_name='Oyiga maksimal tahlillar')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obuna rejasi',
                'verbose_name_plural': 'Obuna rejalari',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('role', models.CharField(choices=[('clinic', 'Klinika'), ('doctor', 'Shifokor'), ('staff', 'Registrator')], default='clinic', max_length=20, verbose_name='Rol')),
                ('specialties', models.JSONField(blank=True, default=list, verbose_name='Mutaxassisliklar')),
                ('subscription_status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol'), ('pending', 'Kutilmoqda')], default='inactive', max_length=20, verbose_name='Obuna holati')),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Obuna muddati')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Trial tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan sana")),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi kirish')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('linked_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to=settings.AUTH_USER_MODEL, verbose_name="Bog'langan shifokor")),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='accounts.subscriptionplan', verbose_name='Obuna rejasi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name="Summa (so'm)")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('receipt_note', models.CharField(blank=True, max_length=255, verbose_name='Chek haqida qisqa eslatma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Tekshiruvchi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounts.subscriptionplan', verbose_name='Reja')),
            ],
            options={
                'verbose_name': "Obuna to'lovi",
                'verbose_name_plural': "Obuna to'lovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='accounts_us_phone_f54457_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_status', 'subscription_expiry'], name='accounts_us_subscri_55a27b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'subscription_status'], name='accounts_us_role_6eb5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['linked_doctor'], name='accounts_us_linked__79d000_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='accounts_us_date_jo_ff39bb_idx'),
        ),
    ]
