# Generated by Django (server makemigrations - index rename for ActiveSession)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activesession'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activesession',
            new_name='accounts_ac_user_id_ca4948_idx',
            old_name='accounts_act_user_id_8a0f0d_idx',
        ),
    ]
