# Generated by Django 5.0.1 on 2026-03-10 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_create_monitoring_demo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('clinic', 'Klinika'), ('doctor', 'Shifokor'), ('staff', 'Registrator'), ('monitoring', 'Bemor monitoring')], default='clinic', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('age', models.CharField(max_length=20, verbose_name='Yosh')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('complaints', models.TextField(blank=True, verbose_name='Shikoyatlar')),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('in-progress', 'Jarayonda'), ('hold', 'Kutish'), ('completed', 'Tugallangan')], db_index=True, default='waiting', max_length=20)),
                ('ticket_number', models.PositiveIntegerField(verbose_name='Navbat raqami')),
                ('arrival_time', models.CharField(blank=True, max_length=20, verbose_name='Kelish vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to=settings.AUTH_USER_MODEL, verbose_name='Shifokor')),
            ],
            options={
                'verbose_name': 'Navbat elementi',
                'verbose_name_plural': 'Navbat elementlari',
                'ordering': ['ticket_number', 'created_at'],
                'indexes': [models.Index(fields=['doctor', 'status'], name='accounts_qu_doctor__34ff05_idx')],
            },
        ),
    ]