# Generated by Django 5.0.1 on 2026-03-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role_queueitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('clinic', 'Klinika'), ('doctor', 'Shifokor'), ('staff', 'Registrator')], default='clinic', max_length=20, verbose_name='Rol'),
        ),
    ]