# Generated by Django 5.2.12 on 2026-04-08 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_0005_activesession_device_lock_fields_0006_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Guruh nomi')),
                ('slug', models.SlugField(blank=True, help_text="Bo'sh qoldirilsa, nomdan avtomatik", max_length=80, unique=True)),
                ('notes', models.TextField(blank=True, verbose_name='Izoh (faqat admin)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Klinika guruhi',
                'verbose_name_plural': 'Klinika guruhlari',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='activesession',
            new_name='accounts_ac_user_id_897257_idx',
            old_name='accounts_act_user_id_2f13ea_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('clinic', 'Klinika')], default='clinic', max_length=20, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='user',
            name='clinic_group',
            field=models.ForeignKey(blank=True, help_text="Bir guruhdagi foydalanuvchilar bemor va tahlillarni bir-biriga ko'radi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.clinicgroup', verbose_name='Klinika guruhi'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['clinic_group'], name='accounts_us_clinic__7b6737_idx'),
        ),
    ]
