# Generated by Django 5.2.14 on 2026-06-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_assign_all_users_fjsti_clinic_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('clinic', 'Klinika'), ('staff', 'Registrator')], default='clinic', max_length=20, verbose_name='Rol'),
        ),
    ]
