# Generated by Django 5.2.14 on 2026-06-29 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_regional_stats_role'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_clinic__9c74aa_idx',
            old_name='accounts_us_clinic__a1b2c3_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='linked_doctor',
            field=models.ForeignKey(blank=True, help_text='Ishlatilmaydi. Registratorlar klinika guruhi (clinic_group) orqali biriktiriladi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to=settings.AUTH_USER_MODEL, verbose_name="(Eskirgan) Bog'langan shifokor"),
        ),
    ]
