# Generated by Django 6.0.2 on 2026-02-04 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_patient_id', models.CharField(blank=True, max_length=255, verbose_name='Bemor ID')),
                ('patient_data', models.JSONField(default=dict, verbose_name="Bemor ma'lumotlari")),
                ('debate_history', models.JSONField(default=list, verbose_name='Munozara tarixi')),
                ('final_report', models.JSONField(default=dict, verbose_name='Yakuniy hisobot')),
                ('follow_up_history', models.JSONField(blank=True, default=list, verbose_name='Keyingi kuzatuv tarixi')),
                ('selected_specialists', models.JSONField(blank=True, default=list, verbose_name='Tanlangan mutaxassislar')),
                ('detected_medications', models.JSONField(blank=True, default=list, verbose_name='Aniqlangan dori-darmonlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='patients.patient', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Tahlil yozuvi',
                'verbose_name_plural': 'Tahlil yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_name', models.CharField(max_length=255, verbose_name='Tashxis nomi')),
                ('feedback', models.CharField(choices=[('more-likely', 'Ehtimollik yuqori'), ('less-likely', 'Ehtimollik past'), ('needs-review', "Ko'rib chiqish kerak"), ('injected-hypothesis', "Qo'shilgan gipoteza")], max_length=50, verbose_name='Fikr')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_feedbacks', to='analyses.analysisrecord', verbose_name='Tahlil')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
            ],
            options={
                'verbose_name': 'Tashxis fikri',
                'verbose_name_plural': 'Tashxis fikrlari',
            },
        ),
        migrations.AddIndex(
            model_name='analysisrecord',
            index=models.Index(fields=['patient'], name='an_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrecord',
            index=models.Index(fields=['created_by'], name='an_created_by_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrecord',
            index=models.Index(fields=['created_at'], name='an_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrecord',
            index=models.Index(fields=['external_patient_id'], name='an_ext_patient_id_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrecord',
            index=models.Index(fields=['created_by', 'created_at'], name='an_created_by_at_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrecord',
            index=models.Index(fields=['patient', 'created_at'], name='an_patient_created_at_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosisfeedback',
            unique_together={('analysis', 'diagnosis_name', 'created_by')},
        ),
    ]
