# Generated by Django 5.0.1 on 2026-03-14 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisUsefulnessFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useful', models.BooleanField(verbose_name='Foydali')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usefulness_feedback', to='analyses.analysisrecord', verbose_name='Tahlil')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_usefulness_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tahlil foydaliligi fikri',
                'verbose_name_plural': 'Tahlil foydaliligi fikrlari',
            },
        ),
        migrations.CreateModel(
            name='AnalysisAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Yaratildi'), ('updated', 'Yangilandi'), ('viewed', "Ko'rilgan")], max_length=20, verbose_name='Amal')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='analyses.analysisrecord', verbose_name='Tahlil')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tahlil audit yozuvi',
                'verbose_name_plural': 'Tahlil audit yozuvlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['analysis'], name='an_audit_analysis_idx'), models.Index(fields=['created_at'], name='an_audit_created_idx')],
            },
        ),
    ]
