# Generated by Django 5.2.14 on 2026-09-03 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_imagingstudyrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisusefulnessfeedback',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usefulness_feedbacks', to='analyses.analysisrecord', verbose_name='Tahlil'),
        ),
        migrations.AlterUniqueTogether(
            name='analysisusefulnessfeedback',
            unique_together={('analysis', 'user')},
        ),
        migrations.AddIndex(
            model_name='analysisusefulnessfeedback',
            index=models.Index(fields=['analysis'], name='an_useful_analysis_idx'),
        ),
    ]
