/**
 * Uzbek Latin (uz-L) → Karakalpak clinical/UI text converter.
 * Used to regenerate accurate kaa locale strings from uzL source.
 */

/** @param {string} text */
export function uzLToKaa(text) {
  if (!text) return text;

  let s = text;

  // Multi-word phrases (order: longest first)
  const phrases = [
    ['qo\'yilgan yoki', 'qosılǵan yamasa'],
    ['o\'tkazilgan', 'ótken'],
    ['o\'tkir', 'ótkir'],
    ['o\'zgargan', 'ózgergen'],
    ['o\'zgarishi', 'ózgerisi'],
    ['o\'zgarishi', 'ózgerisi'],
    ['o\'lchaganda', 'ólshegende'],
    ['o\'lchanmaydi', 'ólshenbeydi'],
    ['o\'t pufagi', 'ót qapshığı'],
    ['o\'t yo\'llari', 'ót jolları'],
    ['o\'t toshi', 'ót tası'],
    ['o\'tirish', 'otırıw'],
    ['o\'ziq-ovqat', 'awqat'],
    ['o\'RVI', 'ÓRVI'],
    ['bo\'g\'imlarda', 'bóǵimlerde'],
    ['bo\'g\'ilish', 'dem qısıw'],
    ['bo\'yin', 'boyın'],
    ['bo\'shash', 'bosıw'],
    ['kechasi', 'ke she'],
    ['kechqurun', 'ke she'],
    ['ovqatdan keyin', 'awqattan keyin'],
    ['ovqatdan', 'awqattan'],
    ['jismoniy zo\'riqishda', 'jismeniy túleklikte'],
    ['jismoniy harakatda', 'jismeniy hárekette'],
    ['jismoniy faollik', 'jismeniy belsendilik'],
    ['nafas qisilishi', 'dem qısıw'],
    ['nafas olishda', 'dem alıwda'],
    ['nafas olish', 'dem alıw'],
    ['nafasda', 'demde'],
    ['nafas ', 'dem '],
    ['ko\'krak og\'rig\'i', 'kókrak awırıǵı'],
    ['ko\'krakda', 'kókrakta'],
    ['ko\'krak ', 'kókrak '],
    ['ko\'ngil aynishi', 'kóngil aynıwı'],
    ['ko\'ngil ', 'kóngil '],
    ['ko\'rish', 'kóriw'],
    ['ko\'z ', 'kóz '],
    ['qo\'l ', 'qol '],
    ['qo\'tirib', 'tıqılap'],
    ['yurak etishmovchiligi', 'júrek jetispewshiligi'],
    ['yurak tez urishi', 'júrek tez urıwı'],
    ['yurak urishi', 'júrek urıwı'],
    ['yurak ', 'júrek '],
    ['bosh og\'rig\'i', 'bas awırıǵı'],
    ['bosh aylanishi', 'bas aylanıwı'],
    ['bosh ', 'bas '],
    ['qorin og\'rig\'i', 'qarıw awırıǵı'],
    ['qorin ', 'qarıw '],
    ['og\'riq', 'awırıq'],
    ['og\'rig\'i', 'awırıǵı'],
    ['og\'riqsiz', 'awırıqsız'],
    ['tez charchash', 'tez shálǵawsızlanıw'],
    ['charchash', 'shálǵawsızlanıw'],
    ['charchoq', 'shálǵawsızlanıw'],
    ['zaiflik', 'kúshsizlik'],
    ['kuchayadi', 'kúshayadı'],
    ['kuchaygan', 'kúshayǵan'],
    ['kamayadi', 'kemeydi'],
    ['paydo bo\'ldi', 'payda boldı'],
    ['paydo bo\'lgan', 'payda bolǵan'],
    ['davom etadi', 'dawam etedi'],
    ['davom etmoqda', 'dawam etip atır'],
    ['davom etuvchi', 'dawam etip atırǵan'],
    ['uzoq davom etadi', 'uzaq dawam etedi'],
    ['tez tekshiruv kerak', 'tez tekseriw kerek'],
    ['tekshiruv kerak', 'tekseriw kerek'],
    ['tekshiruv', 'tekseriw'],
    ['shubha', 'shúbha'],
    ['bemor', 'nawqas'],
    ['shifokor', 'shıpaker'],
    ['kasallik', 'kesellik'],
    ['davolash', 'emlew'],
    ['davolangan', 'emlengen'],
    ['ishitaha yo\'q', 'ishtaha joq'],
    ['ishtaha', 'ishtaha'],
    ['vazn tushgan', 'salmaǵı túsken'],
    ['vazn tushishi', 'salmaǵ túsishi'],
    ['vazn ', 'salmaǵ '],
    ['hayz ', 'ayallıq '],
    ['homiladorlik', 'júkemlik'],
    ['siydik', 'sidik'],
    ['buyrak', 'böwrek'],
    ['jigar', 'peyen'],
    ['terida', 'teriде'],
    ['qon bosimi', 'qan basımı'],
    ['isitma', 'qızıw'],
    ['yo\'tal', 'jılleniw'],
    ['yo\'q ', 'joq '],
    ['yo\'q.', 'joq.'],
    ['mavjud', 'bar'],
    ['kerak', 'kerek'],
    ['va ', 'hám '],
    [' yoki ', ' yamasa '],
    ['bilan', 'menen'],
    ['uchun', 'ushın'],
    ['dan keyin', 'tan keyin'],
    ['dan ', 'dan '],
    ['da ', 'da '],
    ['de ', 'de '],
    ['ni ', 'ni '],
    ['ga ', 'ǧa '],
    ['dan', 'dan'],
    ['tez-tez', 'tez-tez'],
    ['oxirgi', 'sońǵı'],
    ['bir necha', 'bir neshe'],
    ['surunkali', 'xronikalıq'],
    ['ertalab', 'ertennen'],
    ['tunda', 'túnде'],
    ['uyda', 'úyde'],
    ['kecha', 'ke she'],
    ['och qoringa', 'qarıw bos'],
    ['qabziyat', 'qabızlıq'],
    ['ich ketish', 'ish ketiwi'],
    ['qusish', 'qusıw'],
    ['najasda', 'najasta'],
    ['yutish', 'jutıw'],
    ['sariq rang', 'sarıq tús'],
    ['epigastriyada', 'epigastriyada'],
    ['stenokardiya', 'stenokardiya'],
    ['infarkt', 'infarkt'],
    ['aritmiya', 'aritmiya'],
    ['gipertenziya', 'gipertenziya'],
    ['diabet', 'diabet'],
    ['insult', 'insult'],
    ['migren', 'migren'],
    ['pnevmoniya', 'pnevmoniya'],
    ['bronxit', 'bronxit'],
    ['astma', 'astma'],
    ['gemorroy', 'gemorroy'],
    ['pankreatit', 'pankreatit'],
    ['gepatit', 'gepatit'],
    ['gastrit', 'gastrit'],
    ['rentgen', 'rentgen'],
    ['natijasi', 'nátiyjesi'],
    ['natijalari', 'nátiyjeleri'],
    ['profilaktik', 'profilaktikalıq'],
    ['kuzatuv', 'baqlaw'],
    ['nazorat', 'nazorat'],
    ['anemnezi', 'anamnez'],
    ['anamnezi', 'anamnez'],
    ['oilada', 'úydegi'],
    ['chekish', 'temeki shekew'],
    ['alkogol', 'alkogol'],
    ['stressda', 'stresste'],
    ['yotganda', 'jatar waqıtta'],
    ['zinadan chiqishda', 'baspaqshadan shıǵıwda'],
    ['dam olishda', 'dem alıwda'],
    ['harakatda', 'hárekette'],
    ['harakat', 'háreket'],
    ['harakati', 'háreketi'],
    ['notekis', 'tek emes'],
    ['hushdan ketish', 'húshten ketiw'],
    ['uvishish', 'úyrew'],
    ['shish', 'shishiw'],
    ['qizarish', 'qızarıw'],
    ['qichishish', 'qıyşıw'],
    ['allergik', 'allergiyalıq'],
    ['infeksiya', 'infektsiya'],
    ['depressiya', 'depessiya'],
    ['uyqu', 'úyqı'],
    ['kayfiyat', 'kayfiyat'],
    ['dori', 'dári'],
    ['retsept', 'retsept'],
    ['qabul qiladi', 'qabıl etedi'],
    ['qabul qilgan', 'qabıl etken'],
    ['real vaqtda', 'real waqıtta'],
    ['maslahat', 'másliyet'],
    ['konsilium', 'konsilium'],
    ['mutaxassis', 'qánige'],
    ['mutaxassislar', 'qánigeler'],
    ['platforma', 'platforma'],
    ['trening', 'trening'],
    ['arxiv', 'arxiv'],
    ['monitoring', 'monitoring'],
    ['registrator', 'registrator'],
    ['klinika', 'klinika'],
    ['parol', 'parol'],
    ['telefon', 'telefon'],
    ['interval', 'interval'],
    ['morfologiya', 'morfologiya'],
    ['ritm', 'ritm'],
    ['puls', 'puls'],
    ['nafas soni', 'dem sanı'],
    ['qon bosimi', 'qan basımı'],
    ['placeholder', 'placeholder'],
    ['Check-up', 'Check-up'],
    ['FAQ', 'FAQ'],
    ['SpO2', 'SpO2'],
    ['AI ', 'AI '],
    ['AI Konsilium', 'AI Konsilium'],
    ['Gastroenterologiya', 'Gastroenterologiya'],
    ['Kardiologiya', 'Kardiologiya'],
    ['Nevrologiya', 'Nevrologiya'],
    ['Terapiya', 'Terapiya'],
    ['Endokrinologiya', 'Endokrinologiya'],
    ['Pulmonologiya', 'Pulmonologiya'],
    ['Nefrologiya', 'Nefrologiya'],
    ['Dermatologiya', 'Dermatologiya'],
    ['Ortopediya', 'Ortopediya'],
    ['Ginekologiya', 'Ginekologiya'],
    ['Urologiya', 'Urologiya'],
    ['Oftalmologiya', 'Oftalmologiya'],
    ['LOR', 'LOR'],
    ['Revmatologiya', 'Revmatologiya'],
    ['Psixiatriya', 'Psixiatriya'],
  ];

  for (const [from, to] of phrases) {
    s = s.split(from).join(to);
  }

  // Single-char Uzbek apostrophe variants
  s = s.replace(/o'/g, 'ó').replace(/g'/g, 'ǵ').replace(/'/g, '');

  // Fix accidental bad replacements
  s = s
    .replace(/báwrek emes, peyen sohasida/g, 'peyen maydanda')
    .replace(/teriде/g, 'teride')
    .replace(/túnде/g, 'túnde')
    .replace(/cawarcawash/g, 'shálǵawsızlanıw')
    .replace(/kecawasi/g, 'ke she')
    .replace(/ishtaba/g, 'ishtaha')
    .replace(/awayz/g, 'ayallıq')
    .replace(/awayallarda/g, 'ayallarda')
    .replace(/cawap/g, 'sol')
    .replace(/awam /g, 'hám ')
    .replace(/pufakcawalar/g, 'puşakchalar')
    .replace(/qorincawa/g, 'qarıw')
    .replace(/Icawak/g, 'Ishak')
    .replace(/ortiqcawa/g, 'artıq');

  return s;
}
