# Generated by Django 5.0.1 on 2026-03-08 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_monitoring_extended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyViewToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Oilaviy ko'rinish token",
                'verbose_name_plural': "Oilaviy ko'rinish tokenlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringLabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(db_index=True, max_length=80, verbose_name='Parametr (Hb, WBC, ...)')),
                ('value', models.CharField(max_length=100, verbose_name='Qiymat')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Birlik')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lab natija',
                'verbose_name_plural': 'Lab natijalar',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Dori nomi')),
                ('dose', models.CharField(blank=True, max_length=100, verbose_name='Doza')),
                ('scheduled_at', models.DateTimeField(db_index=True, verbose_name='Vaqt')),
                ('given_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dori eslatma',
                'verbose_name_plural': 'Dori eslatmalar',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='vitalreading',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'Vital oʻqish', 'verbose_name_plural': 'Vital oʻqishlar'},
        ),
        migrations.RenameIndex(
            model_name='alarm',
            new_name='monitoring__patient_27e308_idx',
            old_name='monitoring_a_patient_7a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='alarm',
            new_name='monitoring__severit_14e9fb_idx',
            old_name='monitoring_a_severit_8b2c3d_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='monitoring__status_55d799_idx',
            old_name='monitoring_d_status_4d0e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='monitoring__room_id_dbbd95_idx',
            old_name='monitoring_d_room_id_5e0f4g_idx',
        ),
        migrations.RenameIndex(
            model_name='monitoringauditlog',
            new_name='monitoring__patient_022008_idx',
            old_name='mon_audit_pm_created_idx',
        ),
        migrations.RenameIndex(
            model_name='monitoringauditlog',
            new_name='monitoring__action_68a71d_idx',
            old_name='mon_audit_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='monitoringnote',
            new_name='monitoring__patient_405017_idx',
            old_name='mon_note_pm_created_idx',
        ),
        migrations.RenameIndex(
            model_name='patientmonitor',
            new_name='monitoring__room_id_11dc1c_idx',
            old_name='monitoring_p_room_id_3c0d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='vitalreading',
            new_name='monitoring__patient_e20d54_idx',
            old_name='monitoring_v_patient_6a0a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='vitalreading',
            new_name='monitoring__timesta_42179a_idx',
            old_name='monitoring_v_timesta_2b0b1c_idx',
        ),
        migrations.AlterField(
            model_name='device',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Qoʻshimcha maʼlumot'),
        ),
        migrations.AlterField(
            model_name='vitalreading',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Xom maʼlumot (debug)'),
        ),
        migrations.AddIndex(
            model_name='patientmonitor',
            index=models.Index(fields=['bed_status'], name='monitoring__bed_sta_fc50e6_idx'),
        ),
        migrations.AddField(
            model_name='familyviewtoken',
            name='patient_monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_tokens', to='monitoring.patientmonitor', verbose_name='Bemor monitor'),
        ),
        migrations.AddField(
            model_name='monitoringlabresult',
            name='patient_monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='monitoring.patientmonitor', verbose_name='Bemor monitor'),
        ),
        migrations.AddField(
            model_name='monitoringmedication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitoring_medications_created', to=settings.AUTH_USER_MODEL, verbose_name='Yozgan'),
        ),
        migrations.AddField(
            model_name='monitoringmedication',
            name='patient_monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='monitoring.patientmonitor', verbose_name='Bemor monitor'),
        ),
    ]
