# Generated by Django 5.0.1 on 2026-03-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_add_medication_lab_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='host',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='IP manzil (TCP ulanish)'),
        ),
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Port (TCP)'),
        ),
        migrations.AlterField(
            model_name='monitoringauditlog',
            name='action',
            field=models.CharField(choices=[('alarm_created', 'Alarm yaratildi'), ('alarm_ack', 'Alarm qabul qilindi'), ('patient_admit', 'Bemor qabul qilindi'), ('patient_discharge', 'Bemor chiqarildi'), ('note_added', "Eslatma qo'shildi"), ('threshold_changed', "Chegara o'zgartirildi"), ('device_assigned', 'Qurilma biriktirildi'), ('quick_action', 'Tez harakat'), ('rapid_response', 'Rapid response')], db_index=True, max_length=30, verbose_name='Amal'),
        ),
    ]
