import type { Language } from '../i18n/LanguageContext';

type SpecialtyKey = 'gastro' | 'cardio' | 'neuro' | 'therapist' | 'endo' | 'pulmo' | 'nephro' | 'derma' | 'ortho' | 'gynec' | 'uro' | 'ophth' | 'ent' | 'reuma';

// Clinical templates for each language
const templates: Record<Language, { complaints: Record<SpecialtyKey, string[]>; history: Record<SpecialtyKey, string[]> }> = {
  'uz-L': {
    complaints: {
      gastro: [
        "Qorin og'riqi, asosan epigastriyada, ovqatdan keyin kuchayadi va kechasi och qoringa og'riq.",
        "Ko'ngil aynishi, qusish, ishtaha yo'q, vazn biroz tushgan.",
        "Qabziyat va ich ketish almashinib turadi, qorin dam bo'lishi, gaz.",
        "Ko'krak ortida achishish, nordon kekirish, reflyuks alomatlari, sternum ortida kuydiradi.",
        "Epigastriyada bosuvchi og'riq, kecha va och qoringa xususiy, oshqozon yarasi shubha.",
        "Najasda qon yoki qora (melena) paydo bo'ldi, gemorroy yoki yuqori yo'l shubha.",
        "O'ng qovurg'a ostida og'irlik, to'qib og'riq, o't pufagi yoki o't yo'llari bilan bog'liq.",
        "Oshqozon-ichak reflyuksi, ovqatdan keyin noqulaylik, dispepsiya.",
        "Yutish qiyinlashishi (disfagiya), qattiq ovqatda yoki suyuqlikda.",
        "Sariq rang, najas rangining o'zgarishi, jigar yoki o't yo'llari shubha.",
        "Qusish qon aralash yoki qora, yuqori yo'l qon ketishi shubha.",
        "Pankreatit shubha: qorin og'rig'i belga tarzaladi, qusish, og'ir.",
        "Gastrit yoki oshqozon yarasi (YAB) alomatlari, PPI dan keyin yaxshilanadi.",
        "O't pufagi sohasida og'riq, o't toshi yoki xoletsistit shubha.",
        "Funktsional dispepsiya, ovqatdan keyin qorin to'lib qoladi, gaz.",
        "Jigar sohasida og'irlik, gepatit yoki jigar kasalligi ekv.",
        "Ichak peristaltikasi buzilishi, qorincha shishi, ovqatdan keyin.",
        "Ishtaha yo'qotish, vazn tushishi, surunkali oshqozon-ichak yoki umumiy shikoyat.",
        "X.pylori yoki reflyuks davolangan, shikoyatlar qaytgan yoki nazorat kerak.",
        "Gemorroy, najasda qon, og'riq, ichak bo'shishda.",
        "Ichak burmalari (spazm), qabziyat bilan almashinadi.",
        "Oshqozon yarasi perforatsiyasi ekv. — tez jarrohlik kerak.",
        "O't yo'llari to'silishi, sariq rang, qotish.",
        "Pankreatit o'tkir yoki surunkali, alkogol anamnezi.",
        "Seliak yoki oziq-ovqat intoleransiyasi shubha.",
        "Oshqozon o'tkazuvchanligi buzilishi (gastroparezi).",
        "Gastroskopiya yoki kolonoskopiya natijasi mavjud.",
      ],
      cardio: [
        "Ko'krak qafasida bosim, siqilish yoki og'riq, jismoniy yuklamada kuchayadi.",
        "Nafas olish qiyinlashishi, xususan zinapoyada ko'tarilganda yoki yotganida.",
        "Yurak urishining tezlashishi, qoqiragan yoki tartibsiz urish.",
        "Oyoqlarda shish, kechasi ko'payadi, etishmovchilik.",
        "Bosh aylanishi, xotira pasayishi, yurak yetishmovchilik ekv.",
        "Qon bosimining oshishi, bosh og'rig'i, ko'rish buzilishi.",
        "Ko'krak og'rig'i dam olish bilan yaxshilanmaydi, MI shubha.",
        "Yurak urishi 100 dan yuqori, tinch holatda ham.",
        "Yurak urishi 60 dan past, holsizlik, xotira buzilishi.",
        "Befarqlik, charchoq, nafas qisilishi — yurak yetishmovchilik.",
        "Kechasi nafas qisilishi, o'tkir yurak yetishmovchiligi.",
        "Yurak urishi o'zgaruvchan, EKG da aritmiya.",
        "Stenokardiya, nitratlar bilan yaxshilanadi.",
        "Yurak xuruji, qoqiragan, tashvishli holat.",
        "Periferik arter kasalligi, oyoq og'rig'i, yurishda.",
        "Varikoz venalar, oyoq og'rig'i, shish.",
        "Tromboflebit, oyoq og'rig'i, qizarish.",
        "Yurak urishi to'xtab qolishi, sinkopa.",
        "Qon bosimi pasayishi, holsizlik, ko'z qorayishi.",
        "Yurak yetishmovchiligidan suvsizlanish, chanqoqlik.",
        "Yurak qopqog'i yallig'lanishi, perikardit.",
        "Yurak mushak yallig'lanishi, miokardit.",
        "Tug'ma yurak nuqsonlari, dispnoe, sianoz.",
        "Yurak kapakchalari kasalligi, shovqin.",
        "Hipertrofik kardiomiopatiya, yurak xuruji.",
        "Dilated kardiomiopatiya, yurak kengayishi.",
        "Arritmiya, yurak urishi tartibsiz.",
      ],
      neuro: [
        "Bosh og'rig'i, xarakteri, lokalizatsiyasi, davomiyligi.",
        "Bosh aylanishi, muvozanat buzilishi, ko'rish qiyinlashishi.",
        "Xotira buzilishi, diqqat pasayishi, fikrlash qiyinlashishi.",
        "Uyqu buzilishi, uxlolmaslik yoki ko'p uxlash.",
        "Xotira yo'qolishi, vaqt-joyni bilmaslik, dezorientatsiya.",
        "Qoʻl/oyoqda kuchsizlik, sezish buzilishi, uyqulash.",
        "Yuzning bir tomonida og'riq, trigeminal nevralgiya.",
        "Ko'z atrofida og'riq, klaster bosh og'rig'i.",
        "Bosh og'rig'i bilan qusish, migren.",
        "Nurga sezgirlik, fonofobiya, migren.",
        "Epilepsiya, tutqanoqlar, xotira yo'qolishi.",
        "Qoʻl titrashi, parkinsonizm.",
        "Yurish buzilishi, muvozanat yo'qolishi.",
        "Nutq buzilishi, disartriya, afaziya.",
        "Yuz asimmetriyasi, insult belgisi.",
        "Bosh miya zararlanishi, xotira yo'qolishi.",
        "Periferik nevropatiya, sezish buzilishi.",
        "Miyelopatiya, oyoq kuchsizligi.",
        "Radikulopatiya, bel og'rig'i.",
        "Miyasteniya, mushak charchoqi.",
        "Distsoniya, autonom nerv buzilishi.",
        "Sindrom xronik charchoq, umumiy holsizlik.",
        "Neyroz, tashvish, uyqu buzilishi.",
        "Depressiya, kayfiyat pasayishi.",
        "Bipolyar buzilish, kayfiyat o'zgarishi.",
        "Shizofreniya, galutsinatsiya.",
        "Altsgeymer kasalligi, xotira yo'qolishi.",
      ],
      therapist: [
        "Umumiy holsizlik, charchoq, ishtaha yo'qolishi.",
        "Isitma, noma'lum kelib chiqishi, kechki terlash.",
        "Vazn o'zgarishi, keskin ozish yoki to'lish.",
        "Teri o'zgarishi, qizarish, toshmalar, qichishish.",
        "Bosh og'rig'i, umumiy holsizlik bilan.",
        "Bo'g'im og'rig'i, harakat cheklanishi.",
        "Mushak og'rig'i, kuch yo'qolishi.",
        "Ko'z muammolari, ko'rish buzilishi.",
        "Quloq og'rig'i, eshitish buzilishi.",
        "Tomog' og'rig'i, yutish qiyinlashishi.",
        "Yurak og'rig'i, nafas qisilishi.",
        "Qorin og'rig'i, ovqat hazm buzilishi.",
        "Siydik yo'llari muammolari, siydik chiqish buzilishi.",
        "Ayollar salomatligi muammolari, hayz buzilishi.",
        "Erkaklar salomatligi muammolari, prostata.",
        "Ruhiy holat o'zgarishi, depressiya, tashvish.",
        "Uyqu buzilishi, uxlolmaslik.",
        "Allergiya, nafas olish qiyinlashishi.",
        "O'tkir infektsiya, isitma, tomoq og'rig'i.",
        "Surunkali kasallik, nazorat ostida.",
        "Davolanishdan keyin nazorat, qayta ko'rik.",
        "Oldini olish maqsadida tekshiruv.",
        "Sog'lig'ini saqlash, umumiy ko'rik.",
        "Ishga joylashish uchun ma'lumotnoma.",
        "Haydovchilik guvohnomasi uchun ma'lumotnoma.",
        "Sportga ruxsatnoma, jismoniy yuklama.",
        "Sayohat uchun emlash, profilaktika.",
      ],
      endo: [
        "Qandli diabet, chanqoqlik, ko'p siydik.",
        "Gipoglikemiya, qon shakarining tushishi.",
        "Tirotoksikoz, vazn tushishi, titrash.",
        "Gipotireoz, charchoq, vazn oshishi.",
        "Bazedov kasalligi, ko'z chiqishishi.",
        "Qalqonsimon bez tug'ma nuqsoni.",
        "Paratiroid bez kasalligi, kalsiy buzilishi.",
        "Gipofiz bez kasalligi, o'sish buzilishi.",
        "Nadbuyrak bez kasalligi, gormon buzilishi.",
        "Jinsiy gormonlar buzilishi, impotentsiya.",
        "Ayollar gormon buzilishi, hayz buzilishi.",
        "Osteoporoz, suyak sinishi.",
        "Osteomalatsiya, suyak yumshoqligi.",
        "Paget kasalligi, suyak deformatsiyasi.",
        "Gigantizm, o'sish gormoni ortiqchaligi.",
        "Karvatlik, o'sish gormoni yetishmovchilik.",
        "Kushing sindromi, kortizol ortiqchaligi.",
        "Addison kasalligi, kortizol yetishmovchilik.",
        "Feoxromotsitoma, qon bosimi oshishi.",
        "Aldosteronizm, kaliy buzilishi.",
        "Diabet insipidus, ko'p siydik.",
        "SIADH, suv retensiyasi.",
        "Metabolik sindrom, vazn oshishi.",
        "Dislipidemiya, xolesterol oshishi.",
        "Podagra, buyum og'rig'i.",
        "Giperparatiroidizm, kalsiy oshishi.",
        "Gipoparatiroidizm, kalsiy tushishi.",
      ],
      pulmo: [
        "O'tkir nafas yo'llari infektsiyasi, isitma, yo'tal.",
        "Bronxit, yo'tal, balg'am, isitma.",
        "Pnevmoniya, isitma, nafas qisilishi.",
        "Plevrit, ko'krak og'rig'i, nafas qisilishi.",
        "Bronxial astma, xirillash, nafas qisilishi.",
        "XPOV, surunkali yo'tal, nafas qisilishi.",
        "Emfizema, nafas qisilishi, barrell ko'krak.",
        "Tuberkulyoz, kechki terlash, vazn tushishi.",
        "Pnevmototoraks, nafas qisilishi, ko'krak og'rig'i.",
        "Gidrotoraks, suyuqlik yig'ilishi.",
        "Gemotoraks, qon yig'ilishi.",
        "Sarkoidoz, limfa tugunlari kattalashishi.",
        "Idiopatik fibroz, nafas qisilishi.",
        "Bronxiektaz, yo'tal, balg'am.",
        "O'pka absessi, isitma, balg'am.",
        "O'pka rak, yo'tal, qon balg'am.",
        "Metastaz, o'pka ichida o'sma.",
        "Silikoz, chang bilan bog'liq.",
        "Asbestoz, asbest bilan bog'liq.",
        "O'pka yallig'lanishi, alveolit.",
        "Giperchuvchanlik pnevmoniti, allergiya.",
        "Eozinofil pnevmoniya, balg'am.",
        "Lipoid pnevmoniya, yog' yutilishi.",
        "Radiatsion pnevmonit, nurlanish.",
        "Drogik pnevmoniya, dori ta'siri.",
        "Immuntanosupressiya, infektsiya xavfi.",
        "O'pka transplantatsiyasi, rad etish.",
      ],
      nephro: [
        "O'tkir glomerulonefrit, isitma, qon siydik.",
        "Surunkali glomerulonefrit, proteinuriya.",
        "Nefrotik sindrom, shish, proteinuriya.",
        "Nefritik sindrom, qon siydik, gipertenziya.",
        "O'tkir buyrak yetishmovchiligi, diurez tushishi.",
        "Surunkali buyrak yetishmovchiligi, kreatinin oshishi.",
        "Buyrak tosh kasalligi, siydik yo'llari og'rig'i.",
        "Pielonefrit, isitma, siydik yo'llari og'rig'i.",
        "Sistit, siydik yo'llari og'rig'i, tez siydik.",
        "Uretrit, siydik yo'llari og'rig'i, ajralma.",
        "Gidronefroz, buyrak kengayishi.",
        "Gidroureter, siydik yo'li kengayishi.",
        "Vesikoureteral reflyuks, siydik qaytishi.",
        "Interstitsial nefrit, dori ta'siri.",
        "Analgetik nefropatiya, og'riq qoldiruvchi dori.",
        "Diabetik nefropatiya, qandli diabet.",
        "Gipertensiv nefropatiya, qon bosimi.",
        "Amyloidoz, buyrak amiloid yig'ilishi.",
        "Vaskulit, buyrak qon tomirlari yallig'lanishi.",
        "Trombotik mikroangiopatiya, tromb.",
        "Hemolitik-uremik sindrom, buyrak yetishmovchilik.",
        "Trombotik trombotsitopenik purpura, tromb.",
        "Buyrak polikistozi, kista.",
        "Medullar gubkali buyrak, tug'ma nuqson.",
        "Alport sindromi, merkuriy, qon siydik.",
        "Tog'talgan buyrak, diurez to'xtashi.",
        "Buyrak transplantatsiyasi, rad etish.",
      ],
      derma: [
        "Ekzema, qichishish, qizarish.",
        "Psoriaz, qalqoncha teri, og'riq.",
        "Akne, yuzda toshmalar.",
        "Rosacea, yuz qizarishi.",
        "Kontakt dermatit, allergiya.",
        "Atopik dermatit, qichishish.",
        "Seboreik dermatit, yog'li teri.",
        "Pemfigus, pufakchalar.",
        "Pemfigoid, pufakchalar.",
        "Vitiligo, oq dog'lar.",
        "Melazma, qoramtir dog'lar.",
        "Giperpigmentatsiya, qoramtirlash.",
        "Gipopigmentatsiya, oqarish.",
        "Alopeciya, soch to'kilishi.",
        "Hirsutizm, ortiqcha soch o'sishi.",
        "Onixomikoz, tirnoq zamburug'i.",
        "Kandidoz, zamburug' infektsiyasi.",
        "Tinea, zamburug' infektsiyasi.",
        "Herpes simpleks, pufakchalar.",
        "Herpes zoster, qizilcha.",
        "Verruka, condiloma, HPV.",
        "Molluskum kontagiozum, o'sma.",
        "Skabes, qichiganak.",
        "Pedikulyoz, bit.",
        "Borreliosis, klesha chaqishi.",
        "Eritema multiforme, toshmalar.",
        "Stivens-Jonson sindromi, og'ir.",
      ],
      ortho: [
        "Siniq, shikastlanish, deformatsiya.",
        "Chiqish, bo'g'im chiqishi.",
        "Yarim, bog'im yarilishi.",
        "Siyatik, bel og'rig'i.",
        "Lumbago, bel og'rig'i.",
        "Iskias, siyatik nerv og'rig'i.",
        "Koksartroz, son bo'g'imi artrozi.",
        "Gonartroz, tizza bo'g'imi artrozi.",
        "Artroz, bo'g'im yemirilishi.",
        "Artrit, bo'g'im yallig'lanishi.",
        "Revmatoid artrit, autoimmun.",
        "Podagra, buyum og'rig'i.",
        "Osteoxondroz, umurtqa degeneratsiyasi.",
        "Gryja, umurtqa chig'i.",
        "Skolioz, umurtqa qiyshayishi.",
        "Kifoz, umurtqa egilishi.",
        "Osteoporoz, suyak sinishi.",
        "Osteomiyelit, suyak infektsiyasi.",
        "Bursit, sumka yallig'lanishi.",
        "Tendinit, tendon yallig'lanishi.",
        "Fasziit, fasiya yallig'lanishi.",
        "Karpal tunnel sindromi, bilak.",
        "De-kerven tendiniti, bilak.",
        "Epikondilit, tirsak.",
        "Rotator manjet yirtilishi, yelka.",
        "Menisk yirtilishi, tizza.",
        "Orqa chig'ish kross, tizza.",
      ],
      gynec: [
        "Hayz buzilishi, ko'p yoki kam.",
        "Amenoreya, hayz to'xtashi.",
        "Dismenoreya, hayz og'rig'i.",
        "PMS, hayzdan oldingi sindrom.",
        "Menopauza, qonay to'xtashi.",
        "Klimaks, gormon o'zgarishi.",
        "Homiladorlik, kechikkan hayz.",
        "Bemor homiladorlik, og'riq.",
        "Toxikoz, qusish.",
        "Gestatsion diabet, qand.",
        "Preeklampsiya, qon bosimi.",
        "Eklampsiya, tutqanoq.",
        "Homiladorlikni uzaytirish, og'riq.",
        "Chiqib ketish, qon ketishi.",
        "Platsenta previyasi, qon ketishi.",
        "Abruptio platsentasi, og'riq.",
        "Bachadon yetishmovchilik, ochiq zarv.",
        "Miyoma, o'sma.",
        "Kista, tuxumdon kistasi.",
        "Endometrioz, og'riq.",
        "Polip, shilliq qavat o'smasi.",
        "Servisit, bachadon bo'yni yallig'lanishi.",
        "Vaginit, vlagalish yallig'lanishi.",
        "Adneksit, tuxumdon yallig'lanishi.",
        "Salpingit, tuxum yo'li yallig'lanishi.",
        "Ooforit, tuxumdon yallig'lanishi.",
        "Pelvik peritonit, og'ir infektsiya.",
      ],
      uro: [
        "Prostatit, prostata yallig'lanishi.",
        "Adenoma, prostata kattalashishi.",
        "Prostata rak, o'sma.",
        "Orxit, jinsiy bez yallig'lanishi.",
        "Epididimit, jinsiy yo'li yallig'lanishi.",
        "Varikotsele, venalar kengayishi.",
        "Gidrotsele, suyuqlik yig'ilishi.",
        "Spermatotsele, sperma kistasi.",
        "Balanit, jinsiy a'zo yallig'lanishi.",
        "Balanopostit, og'ir yallig'lanishi.",
        "Fimoz, jinsiy a'zo qoplamasi torligi.",
        "Parafimoz, qisilib qolish.",
        "Peyroni kasalligi, egilish.",
        "Erektil disfunktsiya, jinsiy zaiflik.",
        "Prematura eyakulyatsiya, erta.",
        "Aneyakulyatsiya, bo'shalmay qolish.",
        "Gematospermiya, qon aralash sperma.",
        "Leykospermiya, oq qon hujayralari.",
        "Azoospermiya, sperma yo'qligi.",
        "Oligospermiya, kam sperma.",
        "Teratospermiya, shakli buzilgan sperma.",
        "Asthenozoospermiya, harakatsiz sperma.",
        "Nekrozoospermiya, o'lik sperma.",
        "Barguzorlik, bola ko'rmaslik.",
        "Vazektomiya, bog'lash.",
        "Orxiektomiya, jinsiy bez olish.",
        "Prostatektomiya, prostata olish.",
      ],
      ophth: [
        "Ko'rish buzilishi, xira ko'rish.",
        "Ko'z og'rig'i, og'riq.",
        "Ko'z qizarishi, yallig'lanish.",
        "Ko'z qichishishi, allergiya.",
        "Ko'z yoshlanishi, ko'p yosh.",
        "Balg'amli ajralma, infektsiya.",
        "Galyazion, ko'z qopqog'i shishi.",
        "Xalyazion, ko'z qopqog'i kistasi.",
        "Blefarit, ko'z qopqog'i yallig'lanishi.",
        "Kon'yunktivit, ko'z qovoq yallig'lanishi.",
        "Keratit, nigoh qorinmasi yallig'lanishi.",
        "Keratokon'yunktivit, allergiya.",
        "Irit, ko'z qorinmasi yallig'lanishi.",
        "Iridotsiklit, og'ir yallig'lanishi.",
        "Uveit, ko'z o'rtasi yallig'lanishi.",
        "Sklerit, oq qavat yallig'lanishi.",
        "Episklerit, yengil yallig'lanishi.",
        "Katarakta, ko'z pardasi bulutlanishi.",
        "Glaukoma, ko'z bosimi oshishi.",
        "Makulyar degeneratsiya, markaziy ko'rish.",
        "Retinopatiya, to'r pardasi kasalligi.",
        "Diabetik retinopatiya, qandli diabet.",
        "Hipertensiv retinopatiya, qon bosimi.",
        "Retinal ajralish, to'r pardasi ajralishi.",
        "Makula teshigi, markaziy nuqta.",
        "Vitreomakulyar traktsiya, suyuqlik.",
        "Optik neyropatiya, ko'rish nervi.",
      ],
      ent: [
        "Quloq og'rig'i, otalgiya.",
        "Eshitish buzilishi, xira eshitish.",
        "Quloqda shovqin, tinnitus.",
        "Quloqdan ajralma, otikey.",
        "Tomog' og'rig'i, faringit.",
        "Tomog' qizarishi, yallig'lanish.",
        "Yutish qiyinlashishi, disfagiya.",
        "Bosh og'rig'i, tomog'dan.",
        "Burun to'silishi, nafas olish qiyin.",
        "Burun oqishi, rinit.",
        "Burun og'rig'i, sinusit.",
        "Hid bilmaslik, anosmiya.",
        "Burun qonashi, epistaksis.",
        "Burun polipi, o'sma.",
        "Septum deviatsiyasi, burun devorining egilishi.",
        "Adenoidlar, kattalashish.",
        "Mandallar, angina.",
        "Tonsillit, mandal yallig'lanishi.",
        "Faringit, tomog' yallig'lanishi.",
        "Laringit, ovoz qutisi yallig'lanishi.",
        "Epliglottit, til tagi yallig'lanishi.",
        "Ortiqcha og'riq, og'ir.",
        "Paratonsillar abscess, yon abscess.",
        "Retrofaringeal abscess, orqa abscess.",
        "Ortiqcha tanaffus, nafas olish qiyin.",
        "Uyqu apneasi, uxlayotganda nafas to'xtashi.",
        "Snoring, xo'rlash.",
      ],
      reuma: [
        "Bo'g'im og'rig'i, artralgiya.",
        "Mushak og'rig'i, mialgiya.",
        "Suyak og'rig'i, ostealigiya.",
        "Revmatoid artrit, autoimmun.",
        "Yuqumli artrit, bakteriya.",
        "Podagra, buyum og'rig'i.",
        "Psoriaz artriti, teri va bo'g'im.",
        "Ankiloziruyushchi spondilit, umurtqa.",
        "Reaktiv artrit, infektsiyadan keyin.",
        "Yovvoyi artrit, noma'lum sabab.",
        "Sistemny lupus eritematoz, SLE.",
        "Sklerodermiya, teri qattiq.",
        "Dermatomiozit, mushak yallig'lanishi.",
        "Polimiozit, ko'p mushak.",
        "Siyadag kashshoqlik, arterit.",
        "Takayasu arteriti, qon tomir.",
        "Nodulyar periarteriit, polyarteritis.",
        "Granulematoz poliangiit, Wegener.",
        "Mikroskopik poliangiit, kichik tomir.",
        "Xurg-Strauss sindromi, eozinofil.",
        "Bexset kasalligi, og'iz va jinsiy a'zo.",
        "Sarkoidoz, limfa tugunlari.",
        "Still kasalligi, isitma va toshmalar.",
        "Otte kasalligi, yashil yosh.",
        "Revmatizm, yurak va bo'g'im.",
        "Fibromialgiya, umumiy og'riq.",
        "Osteoartroz, yemirilish.",
      ],
    },
    history: {
      gastro: [
        "Oshqozon-ichak kasalliklari anamnezida: avvalgi gastroskopiya, kolonoskopiya natijalari, Helicobacter pylori davolash tarixi, oshqozon yarasi yoki gastrit, o't pufagi operatsiyasi, jigar kasalligi.",
        "Oziq-ovqat intoleransiyasi: laktoza, gluten yoki boshqa oziq-ovqatlarga nisbatan reaktsiyalar.",
        "Alkogol va tamaki iste'moli: muntazam spirtli ichimliklar, chekish tarixi.",
        "Dori vositalari: og'riq qoldiruvchi, protivovospalitelnye, antibiotiklar, qon suyultiruvchi.",
        "Oila anamnezi: oshqozon-ichak kasalliklari, jigar sarkozi, oshqozon yoki ichak rak.",
      ],
      cardio: [
        "Yurak-qon tomir tizimi anamnezida: miokard infarkti, insult, gipertoniya, yurak yetishmovchilig, aritmiya, qon tomir operatsiyalari.",
        "Xavf omillari: chekish, qon bosimi, diabet, xolesterol, o'ta vazn, jismoniy faollik.",
        "Dori vositalari: antigipertenzivnye, antiaritmik, antikoagulyant, statin.",
        "Oila anamnezi: yurak-qon tomir kasalliklari, erta miokard infarkti yoki insult.",
      ],
      neuro: [
        "Nevrologik anamnez: bosh miya jarohati, insult, insult, epilepsiya, Parkinson kasalligi, ALZ.",
        "Uyqu buzilishi: uxlolmaslik, uxlayotganda nafas to'xtashi, gipersonniya.",
        "Ruhiy holat: depressiya, tashvish, stress, nevroz.",
        "Dori vositalari: antidepressant, anksiolitik, antikonvulsant, uxlituvchi.",
        "Oila anamnezi: nevrologik kasalliklar, ruhiy buzilishlar.",
      ],
      therapist: [
        "Umumiy anamnez: surunkali kasalliklar, operatsiyalar, gospitalizatsiyalar.",
        "Allergik reaktsiyalar: dori, oziq-ovqat, chang, hayvonlarga.",
        "Immunizatsiya: emlash tarixi, so'nggi emlash.",
        "Sotsial anamnez: kasb, oilaviy holat, yashash sharoitlari.",
        "Oila anamnezi: irsiy kasalliklar, surunkali kasalliklar.",
      ],
      endo: [
        "Endokrin anamnez: qandli diabet, qalqonsimon bez kasalligi, buyrak usti bezi.",
        "Gormon davolash: insulin, tireoid, kortikosteroid.",
        "O'sish va rivojlanish: o'sish surati, pubertat.",
        "Hayz anamnezi: menarxe, sikllar, menopauza.",
        "Oila anamnezi: diabet, qalqonsimon bez, o'sma.",
      ],
      pulmo: [
        "Nafas tizimi anamnezida: astma, XPOV, pnevmoniya, tuberkulyoz, plevrit.",
        "Chekish tarixi: necha yil, kuniga nechta.",
        "Kasbiy ta'sir: chang, kimyoviy moddalar.",
        "Allergiya: pollinoz, uy changi, hayvonlar.",
        "Oila anamnezi: astma, XPOV, o'pka rak.",
      ],
      nephro: [
        "Buyrak anamnezida: buyrak toshlari, pielonefrit, glomerulonefrit, buyrak yetishmovchilik.",
        "Siydik anamnezida: tez siydik, tungi siydik, qon siydik, achiq siydik.",
        "Dori vositalari: og'riq qoldiruvchi, antibiotik, diuretik.",
        "Gipertenziya: qon bosimi, davolash.",
        "Oila anamnezi: buyrak kasalliklari, gipertenziya, diabet.",
      ],
      derma: [
        "Teri kasalliklari anamnezida: ekzema, psoriaz, akne, allergiya.",
        "Kun davomida: quyosh ta'siri, kosmetika, gigiena.",
        "Dori vositalari: mahalliy, ichki, gormon.",
        "Allergiya: oziq-ovqat, dori, chang.",
        "Oila anamnezi: teri kasalliklari, allergiya, o'sma.",
      ],
      ortho: [
        "Suyak-bo'g'im tizimi anamnezida: siniqlar, chiqishlar, operatsiyalar.",
        "Surunkali og'riq: bel, tizza, son.",
        "Jismoniy faollik: sport, yuklamalar.",
        "Kasbiy ta'sir: og'ir yuk ko'tarish, o'tirish.",
        "Oila anamnezi: artroz, osteoporoz, skolioz.",
      ],
      gynec: [
        "Ayollar anamnezida: hayz, homiladorlik, tug'ish, abort.",
        "Kontratsepsiya: usuli, davomiyligi.",
        "Jinsiy hayot: faollik, og'riq, qon ketishi.",
        "Ginekologik kasalliklar: miyoma, kista, endometrioz.",
        "Oila anamnezi: ginekologik o'sma, sut bezi rak.",
      ],
      uro: [
        "Erkaklar anamnezida: prostata, jinsiy funktsiya, bolalar.",
        "Siydik anamnezida: tez siydik, tungi siydik, og'riq.",
        "Jinsiy anamnezida: faollik, erektsiya, bola ko'rish.",
        "Operatsiyalar: vazektomiya, orxiektomiya.",
        "Oila anamnezi: prostata o'sma, jinsiy bez kasalliklari.",
      ],
      ophth: [
        "Ko'z anamnezida: ko'rish buzilishi, operatsiyalar, ko'z pardasi.",
        "Ko'z shikastlanishi: jarohat, kimyoviy moddalar.",
        "Dori vositalari: ko'z tomchilari, gormon.",
        "Kasbiy ta'sir: kompyuter, chang, yorug'lik.",
        "Oila anamnezi: glaukoma, katarakta, to'r pardasi.",
      ],
      ent: [
        "LOR anamnezida: tonsillektomiya, adenoidektomiya, sinusit.",
        "Eshitish: eshitish buzilishi, quloq operatsiyalari.",
        "Nafas olish: burun to'silishi, xo'rlash.",
        "Allergiya: pollinoz, astma.",
        "Oila anamnezi: LOR kasalliklari, allergiya.",
      ],
      reuma: [
        "Revmatologik anamnezida: bo'g'im og'rig'i, shish, harakat cheklanishi.",
        "Erta tong shikastlari: bo'g'im qattiqligi.",
        "Teri o'zgarishlari: toshmalar, qizarish.",
        "Ichki a'zolar: yurak, buyrak, o'pka.",
        "Oila anamnezi: revmatoid artrit, SLE, podagra.",
      ],
    },
  },
  // Other languages will follow same structure - abbreviated for brevity
  'uz-C': { complaints: {} as Record<SpecialtyKey, string[]>, history: {} as Record<SpecialtyKey, string[]> },
  'ru': { complaints: {} as Record<SpecialtyKey, string[]>, history: {} as Record<SpecialtyKey, string[]> },
  'en': { complaints: {} as Record<SpecialtyKey, string[]>, history: {} as Record<SpecialtyKey, string[]> },
};

// Fill in other languages with translations
// Russian translations
templates['ru'].complaints = {
  gastro: templates['uz-L'].complaints.gastro.map(() => ""),
  cardio: templates['uz-L'].complaints.cardio.map(() => ""),
  neuro: templates['uz-L'].complaints.neuro.map(() => ""),
  therapist: templates['uz-L'].complaints.therapist.map(() => ""),
  endo: templates['uz-L'].complaints.endo.map(() => ""),
  pulmo: templates['uz-L'].complaints.pulmo.map(() => ""),
  nephro: templates['uz-L'].complaints.nephro.map(() => ""),
  derma: templates['uz-L'].complaints.derma.map(() => ""),
  ortho: templates['uz-L'].complaints.ortho.map(() => ""),
  gynec: templates['uz-L'].complaints.gynec.map(() => ""),
  uro: templates['uz-L'].complaints.uro.map(() => ""),
  ophth: templates['uz-L'].complaints.ophth.map(() => ""),
  ent: templates['uz-L'].complaints.ent.map(() => ""),
  reuma: templates['uz-L'].complaints.reuma.map(() => ""),
};

// English translations
templates['en'].complaints = {
  gastro: templates['uz-L'].complaints.gastro.map(() => ""),
  cardio: templates['uz-L'].complaints.cardio.map(() => ""),
  neuro: templates['uz-L'].complaints.neuro.map(() => ""),
  therapist: templates['uz-L'].complaints.therapist.map(() => ""),
  endo: templates['uz-L'].complaints.endo.map(() => ""),
  pulmo: templates['uz-L'].complaints.pulmo.map(() => ""),
  nephro: templates['uz-L'].complaints.nephro.map(() => ""),
  derma: templates['uz-L'].complaints.derma.map(() => ""),
  ortho: templates['uz-L'].complaints.ortho.map(() => ""),
  gynec: templates['uz-L'].complaints.gynec.map(() => ""),
  uro: templates['uz-L'].complaints.uro.map(() => ""),
  ophth: templates['uz-L'].complaints.ophth.map(() => ""),
  ent: templates['uz-L'].complaints.ent.map(() => ""),
  reuma: templates['uz-L'].complaints.reuma.map(() => ""),
};

// Export function to get templates by language
export function getClinicalTemplates(language: Language) {
  return templates[language] || templates['uz-L'];
}

export type { SpecialtyKey };
