/** Mutaxassislik (shablonlar) — shikoyat va anamnez shablonlari konfiguratsiyasi */

export type SpecialtyKey =
    | 'gastro' | 'cardio' | 'neuro' | 'therapist' | 'endo' | 'pulmo'
    | 'nephro' | 'derma' | 'ortho' | 'gynec' | 'uro' | 'ophth' | 'ent' | 'reuma' | 'psych'
    | 'surgeon' | 'neurosurg' | 'cardiosurg' | 'vascular' | 'plastic' | 'maxillofacial'
    | 'onco' | 'pedia' | 'neonat' | 'hemat' | 'infect' | 'emergency'
    | 'radiology' | 'allergy' | 'geriatr' | 'dentistry' | 'mammo' | 'procto'
    | 'phthisio' | 'narcology' | 'rehab' | 'sport' | 'hepat';

export interface SpecialtyConfig {
    complaintCount: number;
    historyCount: number;
    labelKey: string;
}

export const SPECIALTY_CONFIG: Record<SpecialtyKey, SpecialtyConfig> = {
    // — Ichki kasalliklar —
    therapist:   { complaintCount: 23, historyCount: 14, labelKey: 'specialty_therapist' },
    gastro:      { complaintCount: 27, historyCount: 21, labelKey: 'specialty_gastro' },
    cardio:      { complaintCount: 24, historyCount: 17, labelKey: 'specialty_cardio' },
    pulmo:       { complaintCount: 19, historyCount: 8,  labelKey: 'specialty_pulmo' },
    nephro:      { complaintCount: 15, historyCount: 7,  labelKey: 'specialty_nephro' },
    endo:        { complaintCount: 17, historyCount: 13, labelKey: 'specialty_endo' },
    neuro:       { complaintCount: 23, historyCount: 15, labelKey: 'specialty_neuro' },
    reuma:       { complaintCount: 9,  historyCount: 3,  labelKey: 'specialty_reuma' },
    derma:       { complaintCount: 15, historyCount: 5,  labelKey: 'specialty_derma' },
    infect:      { complaintCount: 16, historyCount: 8,  labelKey: 'specialty_infectious' },
    hemat:       { complaintCount: 14, historyCount: 7,  labelKey: 'specialty_hematologist' },
    allergy:     { complaintCount: 12, historyCount: 6,  labelKey: 'specialty_allergy_immunology' },
    hepat:       { complaintCount: 14, historyCount: 7,  labelKey: 'specialty_hepatologist' },
    geriatr:     { complaintCount: 14, historyCount: 8,  labelKey: 'specialty_geriatrician' },
    phthisio:    { complaintCount: 12, historyCount: 6,  labelKey: 'specialty_phthisiology' },
    onco:        { complaintCount: 18, historyCount: 10, labelKey: 'specialty_oncologist' },
    // — Jarrohlik —
    surgeon:     { complaintCount: 20, historyCount: 10, labelKey: 'specialty_surgeon' },
    neurosurg:   { complaintCount: 15, historyCount: 8,  labelKey: 'specialty_neurosurgeon' },
    cardiosurg:  { complaintCount: 15, historyCount: 8,  labelKey: 'specialty_cardiothoracic_surgery' },
    vascular:    { complaintCount: 14, historyCount: 7,  labelKey: 'specialty_vascular_surgery' },
    plastic:     { complaintCount: 12, historyCount: 6,  labelKey: 'specialty_plastic_surgery' },
    maxillofacial: { complaintCount: 12, historyCount: 6, labelKey: 'specialty_maxillofacial' },
    ortho:       { complaintCount: 13, historyCount: 5,  labelKey: 'specialty_ortho' },
    // — Mutaxassisliklar —
    gynec:       { complaintCount: 11, historyCount: 5,  labelKey: 'specialty_gynec' },
    uro:         { complaintCount: 11, historyCount: 4,  labelKey: 'specialty_uro' },
    ophth:       { complaintCount: 10, historyCount: 3,  labelKey: 'specialty_ophth' },
    ent:         { complaintCount: 10, historyCount: 3,  labelKey: 'specialty_ent' },
    dentistry:   { complaintCount: 14, historyCount: 6,  labelKey: 'specialty_dentistry' },
    mammo:       { complaintCount: 12, historyCount: 6,  labelKey: 'specialty_mammologist' },
    procto:      { complaintCount: 12, historyCount: 5,  labelKey: 'specialty_proctologist' },
    pedia:       { complaintCount: 18, historyCount: 10, labelKey: 'specialty_pediatrician' },
    neonat:      { complaintCount: 14, historyCount: 8,  labelKey: 'specialty_neonatologist' },
    psych:       { complaintCount: 18, historyCount: 8,  labelKey: 'specialty_psychiatrist' },
    narcology:   { complaintCount: 14, historyCount: 8,  labelKey: 'specialty_narcology' },
    emergency:   { complaintCount: 18, historyCount: 8,  labelKey: 'specialty_emergency' },
    radiology:   { complaintCount: 10, historyCount: 5,  labelKey: 'specialty_radiology' },
    rehab:       { complaintCount: 12, historyCount: 6,  labelKey: 'specialty_physical_medicine' },
    sport:       { complaintCount: 12, historyCount: 6,  labelKey: 'specialty_sports_medicine' },
};

/** Dropdown tartibi — mantiqiy guruhlar bo'yicha */
export const SPECIALTY_ORDER: SpecialtyKey[] = [
    'therapist', 'gastro', 'cardio', 'pulmo', 'nephro', 'endo', 'neuro', 'reuma',
    'derma', 'infect', 'hemat', 'allergy', 'hepat', 'geriatr', 'phthisio', 'onco',
    'surgeon', 'neurosurg', 'cardiosurg', 'vascular', 'plastic', 'maxillofacial', 'ortho',
    'gynec', 'uro', 'ophth', 'ent', 'dentistry', 'mammo', 'procto',
    'pedia', 'neonat', 'psych', 'narcology', 'emergency', 'radiology', 'rehab', 'sport',
];

/** i18n kaliti topilmasa ishlatiladigan fallback shablonlar (yangi mutaxassisliklar) */
export const FALLBACK_COMPLAINT_TEMPLATES: Partial<Record<SpecialtyKey, string[]>> = {
    surgeon: [
        "O'tkir qorin og'rig'i, qattiq qorin, qusish — o'tkir qorin shubhasi, tez jarrohlik konsultatsiyasi.",
        "Appenditsit shubhasi: o'ng qorin pastki qismida og'riq, isitma, qusish, Leukotsitoz.",
        "Chandiq (gerniya) — og'irlik ko'tarishda yoki zo'riqishda chiqib qoladi, og'riq bilan.",
        "O't pufagi toshlari: o'ng qovurg'a ostida o'tkir og'riq xuruji, ko'ngil aynishi, isitma.",
        "Perforatsiya shubhasi: keskin qorin og'rig'i, qattiq qorin, peritonit belgilari — shoshilinch.",
        "Ichak to'silishi: qorin og'rig'i, qusish, najas va gaz chiqmaydi, qorin shishi.",
        "Oshqozon yarasi perforatsiyasi: keskin epigastrik og'riq, qattiq qorin, qon ketishi.",
        "Gemorroy yoki anal fissura: najasda qon, defekatsiyada og'riq, ichakda og'irlik.",
        "Tiroid bez noduli yoki struma — bo'yin oldida bo'rtma, yutish qiyinligi, nafas qisilishi.",
        "Ko'krak bezi o'simtasi yoki shubha — palpatsiyada tugun, teri o'zgarishi.",
        "Teri yoki yumshoq to'qimalar o'simtasi — o'sish, og'riq, rang o'zgarishi.",
        "Travma keyin ichki qon ketishi shubhasi — qorin shishi, gemodinamik buzilish.",
        "O'tkir xoletsistit: o'ng qovurg'a ostida og'riq, isitma, Murphy belgisi ijobiy.",
        "Divertikulit: chap qorin pastki qismida og'riq, isitma, qabziyat.",
        "Pankreatik massa yoki o'tkir pankreatit — jarrohlik baholash kerak.",
        "Oshqozon yoki o'n ikki barmoqli ichak yarasi — qon ketishi, perforatsiya xavfi.",
        "Rektal qon ketish, kolorektal o'simta shubhasi — kolonoskopiya kerak.",
        "Operatsiyadan keyin og'riq, isitma, chandiq joyida qizarish — postoperativ asorat.",
        "Limfa tugunlari kattalashgan, biopsiya yoki eksiziya kerak.",
        "Jarrohlik konsultatsiyasi: operatsiya rejalashtirilgan yoki davolash usuli tanlash.",
    ],
    neurosurg: [
        "Bosh og'rig'i kuchli, qusish, papilla o'demi — intrakranial bosim oshishi shubhasi.",
        "Bosh miya o'simtasi shubhasi: bosh og'rig'i, nevrologik defitsit, epilepsiya xurujlari.",
        "Orqa miya kompressiyasi: bel og'rig'i, oyoqda kuchsizlik, siyish buzilishi.",
        "Subdural yoki epidural gematoma — travma keyin ong buzilishi, bosh og'rig'i.",
        "Gidrotsefaliya: bosh kattalashishi (bolada), bosh og'rig'i, ko'rish pasayishi.",
        "Chiari malformatsiyasi: bosh og'rig'i, boyin og'rig'i, ko'ngil aynishi.",
        "Disk herniyasi — jarrohlik: bel/bo'yin og'rig'i, radikulopatiya, konservativ davolash samarasiz.",
        "Spinal stenoz: yurishda og'riq, orqaga egilganda yaxshilanadi (neurogenik claudication).",
        "Anevrizma rupturasi shubhasi: «eng yomon» bosh og'rig'i, qattiq bo'yin.",
        "Bosh miya abscessi: isitma, bosh og'rig'i, fokal nevrologik belgilar.",
        "Kranioplastika yoki shunt operatsiyasi keyin kuzatuv.",
        "Neyrojarrohlik konsultatsiyasi: operatsiya rejalashtirilgan.",
    ],
    cardiosurg: [
        "Ko'krak og'rig'i, nafas qisilishi — koronar arteriya kasalligi, bypass shubhasi.",
        "Yurak klapan kasalligi: nafas qisilishi, charchash, ko'krak og'rig'i, sistolik shovqin.",
        "Aorta anevrizmasi: ko'krak yoki qorin og'rig'i, pulsatsiya, KT angiografiya kerak.",
        "O'tkir aorta disseksiyasi: keskin ko'krak og'rig'i, orqaga tarqaladi — shoshilinch.",
        "Atrial septal defect (ASD) yoki VSD — shovqin, nafas qisilishi, reparatsiya kerak.",
        "Yurak yetishmovchiligi — klapan almashtirish yoki reparatsiya baholash.",
        "Pulmonar emboliya — jarrohlik emboliektomiya shubhasi.",
        "Ko'krak qafasi travmasi, pnevmotoraks — torakotomiya kerak bo'lishi mumkin.",
        "Mediastinal massa — biopsiya yoki rezektsiya.",
        "Stent yoki bypass operatsiyasi keyin og'riq, nafas qisilishi.",
        "Ko'krak og'rig'i jismoniy zo'riqishda — koronar bypass konsultatsiyasi.",
        "Yurak transplantatsiyasi ro'yxatida yoki keyin kuzatuv.",
        "Torakoskopik yoki ochiq ko'krak qafasi operatsiyasi rejalashtirilgan.",
        "Perikardial effuz — perikardiosentez yoki operatsiya.",
        "Kardiotorakal jarrohlik konsultatsiyasi.",
    ],
    vascular: [
        "Oyoq og'rig'i yurishda, dam olishda yaxshilanadi — periferik arterial kasallik (PAK).",
        "Oyoq sovuqligi, rang o'zgarishi, og'riq — kritik ishemiya shubhasi.",
        "Varikoz venalar, og'riq, shish, teri o'zgarishi.",
        "Chuqur venalar trombozi (TVT): oyoq shishi, og'riq, qizish.",
        "Karotid arteriya stenozi: insult xavfi, amaurosis fugax.",
        "Aorta anevrizmasi: qorin og'rig'i, pulsatsiya, KT kerak.",
        "Diabetik oyoq: yaralar, gangrena xavfi, amputatsiya baholash.",
        "Lymphoedema: oyoq yoki qo'l shishi, og'irlik.",
        "Raynaud fenomeni: sovuqqa qarshi oyoq/qo'l rang o'zgarishi.",
        "Arteriovenoz malformatsiya — shish, og'riq, qon ketishi.",
        "Endovaskulyar yoki ochiq operatsiya rejalashtirilgan.",
        "Stent yoki bypass keyin oyoq og'rig'i qaytgan.",
        "Trombektomiya yoki anevrizma reparatsiyasi kerak.",
        "Qon tomir jarrohligi konsultatsiyasi.",
    ],
    plastic: [
        "Yuz yoki tanada chandiq (skar) — estetik yoki funksional tuzatish.",
        "Kuyish jarohati keyin rekonstruksiya — kontraktura, cheklangan harakat.",
        "Ko'krak rekonstruksiyasi — mastektomiya keyin yoki konjenital.",
        "Rinoplastika yoki septoplastika — nafas qiyinligi yoki estetik.",
        "O'tkir yuz jarohati — laceratsiya, rekonstruksion jarrohlik.",
        "Cleft lip/palate (tug'ma og'iz yoriq) — rekonstruksiya.",
        "Teri o'simtasi eksiziyasi va plastik yopish.",
        "Lipoma yoki ateroma — olib tashlash.",
        "Ginekomastiya — ko'krak bezining kattalashishi.",
        "Abdominoplastika yoki lipektomiya — qorin terisi ortiqcha.",
        "Mikrojarrohlik — replantatsiya yoki free flap.",
        "Plastik jarrohlik konsultatsiyasi.",
    ],
    maxillofacial: [
        "Jag' sinishi yoki chandiq — travma keyin, og'riq, ishtaha buzilishi.",
        "Tish chiqarish qiyinligi (impacted) — og'riq, shish, infeksiya.",
        "TMJ (chaynash bo'g'imi) og'rig'i — ochish cheklangan, xirillash.",
        "Yuz sinishi — orbital, zigoma, Le Fort fraktura.",
        "Og'iz yoki jag' o'simtasi — biopsiya yoki rezektsiya.",
        "Sialadenit yoki tukun toshi — oqiz suyuqligi bez og'rig'i.",
        "Osteomiyelit jag' suyagi — og'riq, isitma, tish harakatchanligi.",
        "Cleft lip/palate rekonstruksiyasi.",
        "Dental implant yoki alveolar rekonstruksiya.",
        "Yuz-jag' jarrohligi konsultatsiyasi.",
        "Apse yoki odontogen infeksiya — shish, isitma.",
        "Orthognathic jarrohlik — jag' notekisligi.",
    ],
    onco: [
        "Palpatsiyada tugun — ko'krak, limfa tuguni yoki boshqa organ.",
        "Vazn tushishi sababsiz, ishtaha yo'q, zaiflik — onkologik shubha.",
        "Kecha terlash, isitma, charchaq — limfoma yoki boshqa onko shubha.",
        "Najasda qon yoki qora, qorin og'rig'i — kolorektal onko shubha.",
        "Doimiy yo'tal, qon aralash — o'pka onko shubha.",
        "Sariq rang (ikterus), qorin og'rig'i — pankreas yoki jigar onko.",
        "Siydikda qon, prostata yoki siydik yo'llari onko.",
        "Bir tomonda bo'g'im og'rig'i va shish — sarkoma shubha.",
        "Teri yoki mo'lda o'sish, rang o'zgarishi — melanoma shubha.",
        "Qon tahlilida anemiya, trombotsitopeniya — gematologik onko.",
        "Oldin onko tashxisi — nazorat, recidiv yoki metastaz shubha.",
        "Kimyoterapiya yoki radioterapiya kursi davom etmoqda.",
        "Stadiyalash uchun PET-KT, biopsiya rejalashtirilgan.",
        "Palliativ yordam — og'riq, nafas qisilishi, yomonlashgan ahvol.",
        "Ikkinchi opinion — davolash rejasi baholash.",
        "Onkologik markerlar oshgan (CEA, CA-125, PSA va h.k.).",
        "Limfadenopatiya — biopsiya kerak.",
        "Onkolog konsultatsiyasi — tashxis tasdiqlash va davolash rejasi.",
    ],
    pedia: [
        "Isitma, yo'tal, burun oqishi — bolada O'RVI, nafas qisilishi.",
        "Ishtaha yo'q, vazn tushishi, zaiflik — bolada surunkali holat.",
        "Qorin og'rig'i, qusish, isitma — appenditsit yoki gastroenterit shubha.",
        "Terida toshma, qichishish — allergiya yoki infeksiya (qizamiq, vetriqella).",
        "Hayz sikli hali boshlanmagan qizda qorin og'rig'i.",
        "Rivojlanish kechikishi — nutq, yurish, motorika.",
        "Diareya va suvsizlanish — bolada ich ketish, qusish.",
        "Quloq og'rig'i, isitma — otitis media.",
        "Nafas qisilishi, xirillash — bronxial astma yoki bronxiolit.",
        "Sariq rang (neonatal ikterus) — bilirubin yuqori.",
        "Tug'ilgandan keyin ko'krak emish muammosi, vazn o'smayapti.",
        "Immunizatsiya kechikishi yoki reaksiya.",
        "Xulq-atvor muammolari — giperaktivlik, diqqat buzilishi.",
        "Bolada qon ketishi, ko'karganlik — gemofiliya yoki trombotsitopeniya.",
        "Pediatrik tekshiruv — sog'lom bola, profilaktika.",
        "O'sish va vazn egri chizig'i past — o'sish kechikishi.",
        "Bolada epilepsiya xurujlari — tutilish, ong buzilishi.",
        "Pediatr konsultatsiyasi — umumiy yoki ixtisoslashtirilgan.",
    ],
    neonat: [
        "Prematur tug'ilish — nafas qiyinligi, RDS, inkubator.",
        "Neonatal ikterus — fototerapiya kerakligi.",
        "Tug'ilgandan keyin isitma yoki gipotermiya.",
        "Emizish muammosi, vazn o'smayapti, suvsizlanish.",
        "Neonatal konvulsiya — metabolik yoki nevrologik sabab.",
        "Meconium aspiratsiya — nafas qiyinligi tug'ilganda.",
        "Neonatal sepsis — isitma, letargiya, qon ketishi.",
        "Do'g'ilgan nuqson — yurak, ichak, yuz (cleft).",
        "Gipoglikemiya — titroq, letargiya, oziqlantirish.",
        "Neonatal sariq va bilirubin nazorati.",
        "Kuzatuv — NICU dan chiqqan, keyingi nazorat.",
        "Neonatal tiriklik bahosi past — reanimatsiya keyin.",
        "Tug'ilganda vazn past (IUGR) — o'sish kuzatuvi.",
        "Neonatolog konsultatsiyasi.",
    ],
    hemat: [
        "Zaiflik, charchash, rangparlik — anemiya shubhasi.",
        "Ko'karganlik, petexiya, qon ketishi — trombotsitopeniya.",
        "Limfa tugunlari kattalashgan — limfoma shubha.",
        "Isitma, tunda terlash, vazn tushishi — gematologik onko.",
        "Ko'krak suyagi og'rig'i — miyeloma shubha.",
        "Qon quyish reaksiyasi yoki qon quyish kerak.",
        "Surunkali limfositlarni oshgan — CLL shubha.",
        "Talassemiya yoki gemoglobinopatiya — oilaviy.",
        "Antikoagulyant terapiya — INR nazorati, qon ketishi.",
        "Splenomegaliya — qorin og'rig'i, to'liqlik hissi.",
        "Gematologik tekshiruv — qon, medulla biopsiyasi.",
        "Kimyoterapiya yoki transplantatsiya rejalashtirilgan.",
        "Politsitemiya — qizilishi, bosh og'rig'i.",
        "Gematolog konsultatsiyasi.",
    ],
    infect: [
        "Isitma uzoq davom etadi, antibiotikka javob bermaydi.",
        "Noma'lum manbali isitma (FUO) — 3 haftadan ortiq.",
        "Tropik yoki sayohat kasalligi — isitma, diareya, teri toshmasi.",
        "TB shubhasi — uzoq yo'tal, vazn tushishi, kecha terlash.",
        "HIV/AIDS — opportunistik infeksiya, CD4 past.",
        "Sepsis shubhasi — isitma, gipotenziya, tachikardiya.",
        "Meningit yoki encephalitis — bosh og'rig'i, qattiq bo'yin, isitma.",
        "Endokardit — isitma, yurak shovqini, petexiya.",
        "Osteomiyelit — suyak og'rig'i, isitma, lokal qizish.",
        "Virusli gepatit — sariq rang, AST/ALT oshgan.",
        "Brucellosis, tif yoki zoonoz — hayvon bilan aloqa.",
        "COVID-19 yoki gripp — isitma, yo'tal, nafas qisilishi.",
        "Antibiotik tanlash — rezistentlik, kultura natijasi.",
        "Immun yetishmovchilik — tez-tez infeksiya.",
        "Infeksion kasalliklar konsultatsiyasi.",
        "Profilaktika — emlash, postekspozitsion profilaktika.",
    ],
    emergency: [
        "Ko'krak og'rig'i o'tkir — infarkt, aorta disseksiyasi, PE shubhasi.",
        "Nafas qisilishi o'tkir — astma, PE, pneumotoraks.",
        "Hushdan ketish — sinkop, insult, aritmiya, gipoglikemiya.",
        "Travma — bosh jarohati, ko'krak, qorin, oyoq sinishi.",
        "Qon ketish — ichki yoki tashqi, gemodinamik buzilish.",
        "Sepsis — isitma, gipotenziya, tachikardiya, letargiya.",
        "O'tkir qorin — appenditsit, perforatsiya, to'silish.",
        "Zaharlanish — modda, dori, griz.",
        "Anafilaksiya — qichishish, shish, nafas qiyinligi.",
        "Insult FAST — yuz, qo'l, nutq buzilishi, tez tekshiruv.",
        "Yurak to'xtab qolish — CPR, defibrillatsiya.",
        "Yuqori energiya travmasi — politravma.",
        "Elektr yoki chaqmoq jarohati.",
        "Bog'lanish yoki cho'kish — suv yoki tutun.",
        "Psixiatrik favqulodda — o'ziga qasd, agressiya.",
        "Bolada isitma va letargiya — sepsis yoki meningit.",
        "Gipertermiya yoki issiq zarba.",
        "Shoshilinch tibbiy yordam — triyaj va stabilizatsiya.",
    ],
    radiology: [
        "Rentgen/KT/MRT buyurtma — indikatsiya va shikoyat.",
        "Ko'krak rentgeni — yo'tal, nafas qisilishi, TB skrining.",
        "Qorin KT — o'tkir qorin, to'silish, o'simta shubha.",
        "Bosh MRT — bosh og'rig'i, insult, o'simta.",
        "Umurtqa pog'onasi MRT — bel/bo'yin og'rig'i, radikulopatiya.",
        "Mammografiya — skrining yoki tugun shubhasi.",
        "USG — qorin, tiroid, buyrak, homiladorlik.",
        "Angiografiya — qon tomir kasalligi, anevrizma.",
        "PET-KT — onkologik stadiyalash.",
        "Radiologik tekshiruv natijasini tushuntirish.",
    ],
    allergy: [
        "Mavsumiy rinit — burun oqishi, akslanma, qichishish.",
        "Bronxial astma — nafas qisilishi, xirillash, allergen bilan.",
        "Teri toshmalari, qichishish — urtikariya, ekzema.",
        "Ovqat allergiyasi — ovqatdan keyin qichishish, qusish, anafilaksiya.",
        "Dori allergiyasi — penitsillin, NSAID reaksiyasi.",
        "Anafilaksiya tarixi — epinefrin avto-inyektor.",
        "Insekt chaqishi reaksiyasi — shish, anafilaksiya.",
        "Allergik kon'yunktivit — ko'z qichishishi, ajralma.",
        "Atopic dermatit — bolada yoki kattada.",
        "Immunoterapiya (ASIT) kursi davom etmoqda.",
        "IgE yuqori, eozinofiliya — allergik shubha.",
        "Allergolog konsultatsiyasi — test va davolash.",
    ],
    geriatr: [
        "Charchash, zaiflik, tushish xavfi — polipragmasiya.",
        "Xotira pasayishi, orientatsiya buzilishi — demans shubha.",
        "Tushish — son yoki qo'l sinishi, qo'rquv.",
        "Polifarmatsiya — 5+ dori, o'zaro ta'sir.",
        "Incontinensiya — siydik yoki najas nazorati yo'q.",
        "Oziqlanish yetishmovchiligi — vazn tushishi, kacheksiya.",
        "Uyqu buzilishi, kechasi chalkashlik (delirium).",
        "Yolg'iz yashash, ijtimoiy izolyatsiya.",
        "Funksional holat pasayishi — ADL cheklangan.",
        "Geriatrik baholash — komprehensiv ko'rik.",
        "Palliativ yordam — og'riq, qadrli hayot.",
        "Osteoporoz va tushish profilaktikasi.",
        "Parkinson yoki surunkali kasallik kuzatuvi.",
        "Geriatr konsultatsiyasi.",
    ],
    dentistry: [
        "Tish og'rig'i — karies, pulpitis, abscess.",
        "Tish qoqilib qolgan yoki chiqmayapti.",
        "Milk tish yoki doimiy tish — og'riq, shish.",
        "Desna qon ketishi, gingivit, parodontit.",
        "Tish sinishi yoki tushishi — travma.",
        "Og'iz hid — halitosis, infeksiya.",
        "Protez yoki implant muammosi.",
        "Ortodontik muammo — tish notekisligi.",
        "Og'iz yoki til yarasi — uzoq davom etadi.",
        "TMJ og'rig'i — chaynash qiyin.",
        "Fluor profilaktikasi, profilaktik ko'rik.",
        "Bolada tish chiqishi — og'riq, isitma.",
        "Stomatologik tekshiruv va davolash rejasi.",
        "Stomatolog konsultatsiyasi.",
    ],
    mammo: [
        "Ko'krakda tugun yoki qattiq joy — o'ng yoki chap.",
        "Ko'krak og'rig'i — hayz oldida yoki doimiy.",
        "Ko'krakdan ajralma — shaffof, qonli yoki yiringli.",
        "Ko'krak terisi o'zgarishi — qattiq, chuqur, apelsin terisi.",
        "Ko'krak bezining kattalashishi yoki asimmetriya.",
        "Mammografiya natijasi — BI-RADS, biopsiya kerak.",
        "Oilada ko'krak yoki tuxumlik onko.",
        "Ginekomastiya — erkakda ko'krak bez kattalashishi.",
        "Laktatsiya — mastit, abscess.",
        "Ko'krak rekonstruksiyasi keyin kuzatuv.",
        "Mammologik USG va biopsiya.",
        "Mammolog konsultatsiyasi.",
    ],
    procto: [
        "Najasda qon — qizil, qora yoki aralash.",
        "Anal og'riq — defekatsiyada, o'tirishda.",
        "Anal fissura — keskin og'riq, qon.",
        "Gemorroy — ichakdan chiqish, og'riq, qon.",
        "Anal qichishish va noqulaylik.",
        "Ichak bo'shish buzilishi — qabziyat yoki inkontinensiya.",
        "Rektal prolaps — ichak chiqib qoladi.",
        "Perianal abscess — og'riq, isitma, shish.",
        "Kolorektal skrining — kolonoskopiya kerak.",
        "Proktologik tekshiruv — rektal ko'rik.",
        "Anal fistula — ajralma, og'riq.",
        "Proktolog konsultatsiyasi.",
    ],
    phthisio: [
        "Uzoq davom etuvchi yo'tal — 3 haftadan ortiq.",
        "Kecha terlash, vazn tushishi, ishtaha yo'q.",
        "Isitma subfebril, charchash — TB shubhasi.",
        "Nafas qisilishi, ko'krak og'rig'i — plevrit.",
        "TB davolangan — nazorat, recidiv shubha.",
        "Kontakt TB bilan — profilaktik tekshiruv.",
        "Rentgen o'zgarishlari — infiltrat, kavitet.",
        "Mantoux yoki IGRA ijobiy.",
        "Multidrug-resistant TB — davolash qiyin.",
        "TB va HIV birga.",
        "Ftiziatriya kuzatuvi — DOT terapiya.",
        "Ftiziatr konsultatsiyasi.",
    ],
    narcology: [
        "Alkogolga qaramlik — ichishni to'xtata olmaydi.",
        "Alkogol sindromi — titroq, terlash, agressiya.",
        "Giyohvand modda ishlatish — opioid, kanabinoid, stimulyator.",
        "Detoksifikatsiya kerak — xavfsiz chiqish.",
        "Reabilitatsiya — qayta ishlatish oldini olish.",
        "Naltrexone yoki metadon terapiyasi.",
        "Psixoaktiv modda overdose — naloxone kerak.",
        "Oilada giyohvandlik tarixi.",
        "Ish yoki oila muammolari — modda bilan bog'liq.",
        "Ikki xil kasallik — psixiatrik va giyohvandlik.",
        "Nikotin qaramligi — chekishni tashlash.",
        "Narkologik kuzatuv va kodlash (agar qo'llanilsa).",
        "Modda testi ijobiy — ish yoki sud.",
        "Narkolog konsultatsiyasi.",
    ],
    rehab: [
        "Insult keyin — falaj, yurish qiyin, nutq buzilishi.",
        "Operatsiya keyin — endoprotez, disk, ligament.",
        "Spinal jarohat — quyruq suyagi, paraplegiya.",
        "Yurak infarkti keyin — kardiopulmoner reabilitatsiya.",
        "Nafas qisilishi — o'pka reabilitatsiyasi.",
        "Og'riq sindromi — bel, bo'yin, fibromialgiya.",
        "Sport jarohati — reabilitatsiya va qaytish.",
        "Bolada rivojlanish kechikishi — motorika, nutq.",
        "Amputatsiya keyin — protez va adaptatsiya.",
        "Parkinson — harakat, muvozanat.",
        "Fizioterapiya va LFK rejalashtirilgan.",
        "Reabilitolog konsultatsiyasi.",
    ],
    sport: [
        "Sport jarohati — bog'lanish yoki mushak yirtilishi.",
        "Tizza og'rig'i — ACL, menisk, patellofemoral.",
        "Yelka og'rig'i — rotator cuff, impingement.",
        "Stress fraktura — oyoq yoki oyoq.",
        "Kontuziya yoki chandiq — sportda.",
        "Overtraining — charchash, ishlash pasayishi.",
        "Sudden cardiac death xavfi — sport tibbiyoti ko'riki.",
        "Doping nazorati — test ijobiy.",
        "Qaytish sportga — jarohat keyin ruxsat.",
        "Gidratatsiya va issiqlik zarba profilaktikasi.",
        "Sport tibbiyoti konsultatsiyasi.",
        "Sportchi uchun profilaktik ko'rik.",
    ],
    hepat: [
        "Sariq rang (ikterus) — jigar yoki o't yo'llari.",
        "Qorin o'ng qismida og'irlik — gepatit, steatoz.",
        "Viral gepatit — HBV, HCV, anamnez.",
        "Alkogolik jigar kasalligi — AST/ALT oshgan.",
        "Siroz — ascites, varikoz, encephalopathy.",
        "Jigar o'simtasi shubhasi — AFP, KT.",
        "Autoimmune gepatit — ANA, IgG yuqori.",
        "Jigar transplantatsiyasi ro'yxatida yoki keyin.",
        "NASH/MAFLD — metabolik sindrom, vazn ortiqcha.",
        "Wilson kasalligi — yosh, neurologik belgilar.",
        "Gepatologik tekshiruv — FibroScan, biopsiya.",
        "Antiviral terapiya — HCV davolash.",
        "Portal gipertensiya — qon ketishi, splenomegaliya.",
        "Gepatolog konsultatsiyasi.",
    ],
};

export const FALLBACK_HISTORY_TEMPLATES: Partial<Record<SpecialtyKey, string[]>> = {
    surgeon: [
        "Oldin qorin operatsiyasi o'tkazilgan (appendektomiya, xoletsistektomiya va h.k.).",
        "Oilada kolorektal onko yoki polipoz tarixi.",
        "Antikoagulyant yoki antiagregantlar qabul qiladi — operatsiya oldidan to'xtatish kerak.",
        "Diabet, yurak kasalligi — periopertiv xavf yuqori.",
        "Oldin umumiy narkoz o'tkazgan, asorat bo'lmagan.",
        "NSAID yoki og'riq qoldiruvchi uzoq qabul qilgan.",
        "Chekish yoki alkogol — jarrohlik xavfini oshiradi.",
        "Oldin gerniya operatsiyasi, recidiv shubha.",
        "Onko anamnezi — oldin rezektsiya yoki kimyoterapiya.",
        "Jarrohlik oldi tekshiruv — qon, EKG, rentgen o'tkazilgan.",
    ],
    neurosurg: [
        "Bosh miya yoki orqa miya operatsiyasi o'tkazilgan.",
        "Shunt (VP shunt) o'rnatilgan, kuzatuvda.",
        "Travmatik bosh jarohati anamnezi.",
        "Oilada anevrizma yoki miya o'simtasi.",
        "Antikoagulyantlar — operatsiya oldidan muhim.",
        "Epilepsiya — dori rejimi, operatsiya rejalashtirilgan.",
        "Oldin radioterapiya — bosh miyaga.",
        "Neyrojarrohlik oldi MRT/KT o'tkazilgan.",
    ],
    cardiosurg: [
        "Koronar arteriya kasalligi — stent yoki bypass tarixi.",
        "Yurak klapan kasalligi — EchoKG da stenoz yoki regurgitatsiya.",
        "Aorta anevrizmasi kuzatuvda — KT angiografiya.",
        "Oilada yurak kasalligi, erta yurak infarkti.",
        "Diabet, gipertenziya — periopertiv xavf.",
        "Oldin ochiq yurak operatsiyasi o'tkazilgan.",
        "Antikoagulyantlar — klapan prosthesis bilan.",
        "Kardiotorakal jarrohlik oldi tekshiruv o'tkazilgan.",
    ],
    vascular: [
        "Periferik arterial kasallik — oyoq og'rig'i, claudication.",
        "TVT yoki TEP tarixi — antikoagulyantlar.",
        "Diabet — oyoq yaralari, mikroangiopatiya.",
        "Chekish — PAK xavfini oshiradi.",
        "Varikoz venalar — oldin operatsiya yoki skleroterapiya.",
        "Karotid stenoz — insult xavfi.",
        "Endovaskulyar yoki ochiq operatsiya tarixi.",
    ],
    plastic: [
        "Oldin plastik jarrohlik yoki rekonstruksiya o'tkazilgan.",
        "Kuyish yoki travma anamnezi.",
        "Keloid yoki gipertrafik chandiq shakllanadi.",
        "Onko anamnezi — mastektomiya keyin rekonstruksiya.",
        "Allergiya — anestetik yoki materialga.",
        "Plastik jarrohlik oldi konsultatsiya o'tkazilgan.",
    ],
    maxillofacial: [
        "Oldin jag' yoki yuz operatsiyasi o'tkazilgan.",
        "Tish chiqarish yoki implant tarixi.",
        "Travma — yuz sinishi.",
        "TMJ disord — oldin davolangan.",
        "Radioterapiya bosh-bo'yin sohasiga.",
        "Yuz-jag' jarrohligi oldi tekshiruv.",
    ],
    onco: [
        "Oldin onko tashxisi qo'yilgan — davolash va stadiya.",
        "Kimyoterapiya, radioterapiya yoki immunoterapiya kurslari.",
        "Oilada onko (ko'krak, kolorektal, prostat va h.k.).",
        "Metastaz shubha — PET-KT rejalashtirilgan.",
        "Palliativ yordam — og'riq nazorati.",
        "Onkologik markerlar kuzatuvda.",
        "Remissiya — nazorat tekshiruvlari.",
        "Ikkinchi opinion yoki davolash rejasi o'zgartirish.",
        "Supportive care — anemiya, neutropeniya.",
        "Onkologik anamnez to'liq hujjatlashtirilgan.",
    ],
    pedia: [
        "Tug'ilish anamnezi — prematur, asphyxia, APGAR.",
        "Immunizatsiya kalendari — to'liq yoki kechikkan.",
        "O'sish va rivojlanish — vazn, bo'y, motorika.",
        "Oilada allergiya, astma yoki onko.",
        "Emizish yoki sun'iy oziqlantirish.",
        "Bolada surunkali kasallik — diabet, epilepsiya.",
        "Pediatrik operatsiya yoki gospitalizatsiya tarixi.",
        "Maktab yoki bog'cha — xulq-atvor, o'qish.",
        "Pediatrik anamnez to'liq.",
        "Ota-ona shikoyati va kuzatuv tarixi.",
    ],
    neonat: [
        "Tug'ilish — gestatsiya haftasi, vazn, APGAR.",
        "NICU da yotgan — RDS, sepsis, ikterus.",
        "Ona kasalliklari — GDM, preeklampsiya, infeksiya.",
        "Neonatal operatsiya yoki malformatsiya.",
        "Emizish — ko'krak yoki sun'iy.",
        "Neonatal skrining — metabolik, eshitish.",
        "Chiqishdan keyin kuzatuv — vazn, sariq.",
        "Neonatologik anamnez.",
    ],
    hemat: [
        "Oldin qon quyish yoki transplantatsiya.",
        "Oilada gematologik kasallik — talassemiya, gemofiliya.",
        "Kimyoterapiya yoki radioterapiya.",
        "Antikoagulyant yoki antiagregantlar.",
        "Splenektomiya o'tkazilgan.",
        "Gematologik tekshiruv — qon, medulla.",
        "Gematologik anamnez.",
    ],
    infect: [
        "Sayohat anamnezi — tropik mintaqa, endemik zona.",
        "HIV yoki immun yetishmovchilik.",
        "TB bilan aloqa yoki oldin TB davolangan.",
        "Antibiotik ishlatilgan — nomi, davomiyligi.",
        "Hayvon bilan aloqa — zoonoz xavfi.",
        "Emlashlar — hepatit, gripp, COVID.",
        "Infeksion kasalliklar anamnezi.",
        "Profilaktik antibiotik yoki profilaktika.",
    ],
    emergency: [
        "Tez yordam chaqirilgan — vaqt va holat.",
        "Allergiya — dori, ovqat, anafilaksiya.",
        "Surunkali kasalliklar — yurak, diabet, epilepsiya.",
        "Hozirgi dorilar — antikoagulyant, insulin.",
        "Travma mexanizmi — balandlik, DTP, urish.",
        "O'tkir holat oldi — qachon boshlangan.",
        "Shoshilinch anamnez — tez yig'ilgan.",
        "Kontakt ma'lumot — qarindosh.",
    ],
    radiology: [
        "Oldin rentgen, KT yoki MRT o'tkazilgan.",
        "Kontrast allergiyasi — yod, gadoliniy.",
        "Buyurtma sababi — shikoyat, tashxis shubhasi.",
        "Homiladorlik — radiatsiya xavfi.",
        "Radiologik tekshiruv tarixi.",
    ],
    allergy: [
        "Oilada allergiya, astma, atopic dermatit.",
        "Mavsumiy yoki doimiy allergiya.",
        "Ovqat yoki dori allergiyasi anamnezi.",
        "Anafilaksiya xuruji — qachon, nima sabab.",
        "Immunoterapiya kursi.",
        "Allergik anamnez.",
    ],
    geriatr: [
        "Polipragmasiya — 5+ dori ro'yxati.",
        "Tushish tarixi — son, qo'l sinishi.",
        "Demans yoki kognitiv pasayish shubha.",
        "Yolg'iz yashash, ijtimoiy qo'llab-quvvatlash.",
        "Funksional holat — yurish, oziq-ovqat, gigiyena.",
        "Oilada demans yoki uzoq umr.",
        "Geriatrik anamnez — komprehensiv.",
        "Palliativ yoki hospice rejimi.",
    ],
    dentistry: [
        "Oldin tish davolash yoki operatsiya.",
        "Protez, implant yoki ortodontiya.",
        "Og'iz gigiyenasi — muntazam tozalash.",
        "Tish chiqarish tarixi.",
        "Stomatologik anamnez.",
        "Bolada tish chiqishi va emizish.",
    ],
    mammo: [
        "Oilada ko'krak yoki tuxumlik onko.",
        "Oldin mammografiya yoki biopsiya.",
        "Gormonal terapiya — KOK, HRT.",
        "Homiladorlik va emizish tarixi.",
        "Ko'krak operatsiyasi tarixi.",
        "Mammologik anamnez.",
    ],
    procto: [
        "Oldin gemorroy yoki anal operatsiya.",
        "Kolorektal skrining — kolonoskopiya.",
        "Qabziyat yoki ichak odatlari.",
        "Oilada kolorektal onko.",
        "Proktologik anamnez.",
    ],
    phthisio: [
        "TB bilan aloqa — oila yoki ish joyi.",
        "Oldin TB davolangan — DOT, muddati.",
        "HIV yoki immun yetishmovchilik.",
        "Mantoux yoki IGRA oldin ijobiy.",
        "Chekish — TB xavfini oshiradi.",
        "Ftiziatrik anamnez.",
    ],
    narcology: [
        "Alkogol yoki modda ishlatish davomiyligi.",
        "Oldin detoks yoki reabilitatsiya.",
        "Oilada giyohvandlik.",
        "Psixiatrik kasallik birga.",
        "Ish yoki huquqiy muammolar.",
        "Narkologik anamnez.",
        "Modda testi tarixi.",
        "Nikotin qaramligi.",
    ],
    rehab: [
        "Insult, travma yoki operatsiya sanasi.",
        "Reabilitatsiya kursi boshlangan yoki tugagan.",
        "Funksional holat — ADL, yurish masofasi.",
        "Og'riq shkalasi va cheklangan harakat.",
        "Reabilitatsiya anamnezi.",
        "Uyda yoki statsionarda LFK.",
    ],
    sport: [
        "Sport turi va yuklamasi.",
        "Oldin sport jarohati va davolash.",
        "Doping testi yoki qoidalarga rioya.",
        "Sport tibbiyoti ko'riki — yurak, EKG.",
        "Sport anamnezi.",
        "Qaytish sportga ruxsat.",
    ],
    hepat: [
        "Viral gepatit — HBV, HCV, davolash.",
        "Alkogol iste'moli — miqdor, davomiylik.",
        "Jigar kasalligi — siroz, steatoz.",
        "Jigar transplantatsiyasi ro'yxati.",
        "Oilada jigar kasalligi.",
        "Antiviral terapiya.",
        "Gepatologik anamnez.",
    ],
};

/** English/Russian fallback when i18n template keys are not yet translated */
export const EN_FALLBACK_COMPLAINT_TEMPLATES: Partial<Record<SpecialtyKey, string[]>> = {
    surgeon: [
        'Acute abdominal pain, rigid abdomen, vomiting — acute abdomen suspected, urgent surgical consult.',
        'Appendicitis suspected: right lower quadrant pain, fever, vomiting, leukocytosis.',
        'Hernia — bulges with lifting or straining, painful.',
        'Gallstones: acute pain under right rib cage, nausea, fever.',
        'Perforation suspected: sudden severe abdominal pain, rigid abdomen, peritonitis — emergency.',
        'Bowel obstruction: abdominal pain, vomiting, no stool or flatus, distension.',
        'Peptic ulcer perforation: acute epigastric pain, rigid abdomen, bleeding.',
        'Hemorrhoids or anal fissure: rectal bleeding, pain on defecation.',
        'Thyroid nodule or goiter — neck swelling, dysphagia, dyspnea.',
        'Breast lump or mass — palpable nodule, skin changes.',
        'Skin or soft tissue mass — growing, painful, color change.',
        'Post-trauma internal bleeding suspected — abdominal distension, hemodynamic instability.',
        'Acute cholecystitis: RUQ pain, fever, positive Murphy sign.',
        'Diverticulitis: left lower quadrant pain, fever, constipation.',
        'Pancreatic mass or acute pancreatitis — surgical evaluation needed.',
        'Gastric or duodenal ulcer — bleeding, perforation risk.',
        'Rectal bleeding, colorectal cancer suspected — colonoscopy needed.',
        'Postoperative pain, fever, redness at incision — surgical complication.',
        'Enlarged lymph nodes — biopsy or excision needed.',
        'Surgical consultation — planned operation or treatment decision.',
    ],
    neurosurg: [
        'Severe headache, vomiting, papilledema — raised intracranial pressure suspected.',
        'Brain tumor suspected: headache, neurological deficit, seizures.',
        'Spinal cord compression: back pain, leg weakness, urinary dysfunction.',
        'Subdural or epidural hematoma — post-trauma altered consciousness.',
        'Hydrocephalus: head enlargement (child), headache, vision loss.',
        'Chiari malformation: headache, neck pain, nausea.',
        'Disc herniation — surgery: back/neck pain, radiculopathy, failed conservative care.',
        'Spinal stenosis: leg pain on walking, relieved by leaning forward.',
        'Aneurysm rupture suspected: worst headache of life, stiff neck.',
        'Brain abscess: fever, headache, focal neurological signs.',
        'Post cranioplasty or shunt — follow-up.',
        'Neurosurgical consultation — planned operation.',
    ],
    cardiosurg: [
        'Chest pain, dyspnea — coronary artery disease, bypass suspected.',
        'Valvular heart disease: dyspnea, fatigue, chest pain, systolic murmur.',
        'Aortic aneurysm: chest or abdominal pain, pulsation, CT angiography needed.',
        'Acute aortic dissection: sudden chest pain radiating to back — emergency.',
        'ASD or VSD — murmur, dyspnea, repair needed.',
        'Heart failure — valve replacement or repair evaluation.',
        'Pulmonary embolism — surgical embolectomy suspected.',
        'Chest trauma, pneumothorax — thoracotomy may be needed.',
        'Mediastinal mass — biopsy or resection.',
        'Post stent or bypass — pain, dyspnea.',
        'Chest pain on exertion — coronary bypass consultation.',
        'Heart transplant listing or post-transplant follow-up.',
        'Thoracoscopic or open chest surgery planned.',
        'Pericardial effusion — pericardiocentesis or surgery.',
        'Cardiothoracic surgery consultation.',
    ],
    vascular: [
        'Leg pain on walking, relieved at rest — peripheral arterial disease (PAD).',
        'Cold leg, color change, pain — critical ischemia suspected.',
        'Varicose veins, pain, swelling, skin changes.',
        'Deep vein thrombosis (DVT): leg swelling, pain, warmth.',
        'Carotid stenosis: stroke risk, amaurosis fugax.',
        'Aortic aneurysm: abdominal pain, pulsation, CT needed.',
        'Diabetic foot: ulcers, gangrene risk, amputation evaluation.',
        'Lymphedema: arm or leg swelling, heaviness.',
        'Raynaud phenomenon: cold-induced color change in fingers/toes.',
        'Arteriovenous malformation — swelling, pain, bleeding.',
        'Endovascular or open surgery planned.',
        'Post stent or bypass — recurrent leg pain.',
        'Thrombectomy or aneurysm repair needed.',
        'Vascular surgery consultation.',
    ],
    plastic: [
        'Facial or body scar — aesthetic or functional correction.',
        'Burn injury reconstruction — contracture, limited movement.',
        'Breast reconstruction — post mastectomy or congenital.',
        'Rhinoplasty or septoplasty — breathing difficulty or aesthetic.',
        'Acute facial trauma — laceration, reconstructive surgery.',
        'Cleft lip/palate — reconstruction.',
        'Skin lesion excision and plastic closure.',
        'Lipoma or atheroma — removal.',
        'Gynecomastia — breast enlargement in male.',
        'Abdominoplasty or lipectomy — excess abdominal skin.',
        'Microsurgery — replantation or free flap.',
        'Plastic surgery consultation.',
    ],
    maxillofacial: [
        'Jaw fracture or laceration — post trauma, pain, eating difficulty.',
        'Difficult tooth extraction (impacted) — pain, swelling, infection.',
        'TMJ pain — limited opening, clicking.',
        'Facial fracture — orbital, zygoma, Le Fort.',
        'Oral or jaw tumor — biopsy or resection.',
        'Sialadenitis or duct stone — salivary gland pain.',
        'Jaw osteomyelitis — pain, fever, tooth mobility.',
        'Cleft lip/palate reconstruction.',
        'Dental implant or alveolar reconstruction.',
        'Oral and maxillofacial consultation.',
        'Abscess or odontogenic infection — swelling, fever.',
        'Orthognathic surgery — jaw malalignment.',
    ],
    onco: [
        'Palpable lump — breast, lymph node or other organ.',
        'Unexplained weight loss, anorexia, weakness — oncologic suspicion.',
        'Night sweats, fever, fatigue — lymphoma or other malignancy.',
        'Rectal bleeding or melena, abdominal pain — colorectal cancer.',
        'Persistent cough, hemoptysis — lung cancer suspected.',
        'Jaundice, abdominal pain — pancreatic or liver cancer.',
        'Hematuria — prostate or urothelial cancer.',
        'Unilateral joint pain and swelling — sarcoma suspected.',
        'Growing mole or skin lesion — melanoma suspected.',
        'Anemia, thrombocytopenia — hematologic malignancy.',
        'Prior cancer diagnosis — surveillance, recurrence or metastasis.',
        'Chemotherapy or radiotherapy in progress.',
        'Staging planned — PET-CT, biopsy.',
        'Palliative care — pain, dyspnea, declining condition.',
        'Second opinion — treatment plan review.',
        'Elevated tumor markers (CEA, CA-125, PSA, etc.).',
        'Lymphadenopathy — biopsy needed.',
        'Oncology consultation — confirm diagnosis and treatment plan.',
    ],
    pedia: [
        'Fever, cough, runny nose — child URI, dyspnea.',
        'Loss of appetite, weight loss, weakness — chronic condition in child.',
        'Abdominal pain, vomiting, fever — appendicitis or gastroenteritis.',
        'Skin rash, itching — allergy or infection (measles, varicella).',
        'Abdominal pain in premenarchal girl.',
        'Developmental delay — speech, walking, motor skills.',
        'Diarrhea and dehydration — vomiting in child.',
        'Ear pain, fever — otitis media.',
        'Dyspnea, wheezing — asthma or bronchiolitis.',
        'Jaundice (neonatal) — elevated bilirubin.',
        'Feeding difficulty, failure to thrive.',
        'Delayed immunization or reaction.',
        'Behavioral problems — hyperactivity, attention deficit.',
        'Bleeding, bruising in child — hemophilia or thrombocytopenia.',
        'Pediatric check-up — healthy child, prevention.',
        'Growth and weight curve low — growth delay.',
        'Seizures in child — convulsion, altered consciousness.',
        'Pediatric consultation.',
    ],
    neonat: [
        'Premature birth — respiratory distress, RDS, incubator.',
        'Neonatal jaundice — phototherapy needed.',
        'Postnatal fever or hypothermia.',
        'Feeding problems, failure to thrive, dehydration.',
        'Neonatal seizures — metabolic or neurological cause.',
        'Meconium aspiration — respiratory distress at birth.',
        'Neonatal sepsis — fever, lethargy, bleeding.',
        'Congenital defect — heart, intestine, cleft.',
        'Hypoglycemia — tremor, lethargy, feeding.',
        'Neonatal jaundice and bilirubin monitoring.',
        'NICU discharge follow-up.',
        'Low Apgar — post resuscitation.',
        'Low birth weight (IUGR) — growth monitoring.',
        'Neonatology consultation.',
    ],
    hemat: [
        'Weakness, fatigue, pallor — anemia suspected.',
        'Bruising, petechiae, bleeding — thrombocytopenia.',
        'Enlarged lymph nodes — lymphoma suspected.',
        'Fever, night sweats, weight loss — hematologic malignancy.',
        'Bone pain — myeloma suspected.',
        'Transfusion reaction or transfusion needed.',
        'Chronic lymphocytosis — CLL suspected.',
        'Thalassemia or hemoglobinopathy — familial.',
        'Anticoagulant therapy — INR monitoring, bleeding.',
        'Splenomegaly — abdominal pain, fullness.',
        'Hematology workup — blood, bone marrow biopsy.',
        'Chemotherapy or transplant planned.',
        'Polycythemia — flushing, headache.',
        'Hematology consultation.',
    ],
    infect: [
        'Prolonged fever, no response to antibiotics.',
        'Fever of unknown origin (FUO) — over 3 weeks.',
        'Tropical or travel-related illness — fever, diarrhea, rash.',
        'TB suspected — chronic cough, weight loss, night sweats.',
        'HIV/AIDS — opportunistic infection, low CD4.',
        'Sepsis suspected — fever, hypotension, tachycardia.',
        'Meningitis or encephalitis — headache, stiff neck, fever.',
        'Endocarditis — fever, heart murmur, petechiae.',
        'Osteomyelitis — bone pain, fever, local warmth.',
        'Viral hepatitis — jaundice, elevated AST/ALT.',
        'Brucellosis, typhoid or zoonosis — animal contact.',
        'COVID-19 or influenza — fever, cough, dyspnea.',
        'Antibiotic selection — resistance, culture results.',
        'Immunodeficiency — recurrent infections.',
        'Infectious disease consultation.',
        'Prevention — vaccination, post-exposure prophylaxis.',
    ],
    emergency: [
        'Acute chest pain — MI, aortic dissection, PE suspected.',
        'Acute dyspnea — asthma, PE, pneumothorax.',
        'Syncope — collapse, stroke, arrhythmia, hypoglycemia.',
        'Trauma — head injury, chest, abdomen, limb fracture.',
        'Bleeding — internal or external, hemodynamic instability.',
        'Sepsis — fever, hypotension, tachycardia, lethargy.',
        'Acute abdomen — appendicitis, perforation, obstruction.',
        'Poisoning — substance, drug, toxin.',
        'Anaphylaxis — itching, swelling, dyspnea.',
        'Stroke FAST — face, arm, speech deficit, urgent evaluation.',
        'Cardiac arrest — CPR, defibrillation.',
        'High-energy trauma — polytrauma.',
        'Electrical or lightning injury.',
        'Drowning or smoke inhalation.',
        'Psychiatric emergency — self-harm, aggression.',
        'Child with fever and lethargy — sepsis or meningitis.',
        'Hyperthermia or heat stroke.',
        'Emergency medicine — triage and stabilization.',
    ],
    radiology: [
        'X-ray/CT/MRI order — indication and complaint.',
        'Chest X-ray — cough, dyspnea, TB screening.',
        'Abdominal CT — acute abdomen, obstruction, mass.',
        'Brain MRI — headache, stroke, tumor.',
        'Spine MRI — back/neck pain, radiculopathy.',
        'Mammography — screening or lump suspicion.',
        'Ultrasound — abdomen, thyroid, kidney, pregnancy.',
        'Angiography — vascular disease, aneurysm.',
        'PET-CT — oncologic staging.',
        'Radiology result interpretation.',
    ],
    allergy: [
        'Seasonal rhinitis — runny nose, sneezing, itching.',
        'Bronchial asthma — dyspnea, wheezing, allergen-related.',
        'Skin rash, itching — urticaria, eczema.',
        'Food allergy — itching, vomiting, anaphylaxis after eating.',
        'Drug allergy — penicillin, NSAID reaction.',
        'Anaphylaxis history — epinephrine auto-injector.',
        'Insect sting reaction — swelling, anaphylaxis.',
        'Allergic conjunctivitis — eye itching, discharge.',
        'Atopic dermatitis — child or adult.',
        'Immunotherapy (SCIT) in progress.',
        'Elevated IgE, eosinophilia — allergic suspicion.',
        'Allergy consultation — testing and treatment.',
    ],
    geriatr: [
        'Fatigue, weakness, fall risk — polypharmacy.',
        'Memory decline, disorientation — dementia suspected.',
        'Falls — hip or arm fracture, fear.',
        'Polypharmacy — 5+ drugs, interactions.',
        'Incontinence — urinary or fecal.',
        'Malnutrition — weight loss, cachexia.',
        'Sleep disturbance, nocturnal confusion (delirium).',
        'Living alone, social isolation.',
        'Functional decline — ADL limited.',
        'Geriatric assessment — comprehensive exam.',
        'Palliative care — pain, quality of life.',
        'Osteoporosis and fall prevention.',
        'Parkinson or chronic disease follow-up.',
        'Geriatrics consultation.',
    ],
    dentistry: [
        'Toothache — caries, pulpitis, abscess.',
        'Impacted or erupting tooth.',
        'Primary or permanent tooth — pain, swelling.',
        'Gum bleeding, gingivitis, periodontitis.',
        'Tooth fracture or avulsion — trauma.',
        'Bad breath — halitosis, infection.',
        'Prosthesis or implant problem.',
        'Orthodontic issue — malocclusion.',
        'Oral or tongue ulcer — prolonged.',
        'TMJ pain — difficulty chewing.',
        'Fluoride prevention, check-up.',
        'Teething in child — pain, fever.',
        'Dental exam and treatment plan.',
        'Dentistry consultation.',
    ],
    mammo: [
        'Breast lump or hard area — right or left.',
        'Breast pain — premenstrual or constant.',
        'Nipple discharge — clear, bloody or purulent.',
        'Breast skin changes — dimpling, orange peel.',
        'Breast enlargement or asymmetry.',
        'Mammography result — BI-RADS, biopsy needed.',
        'Family history breast or ovarian cancer.',
        'Gynecomastia — male breast enlargement.',
        'Lactation — mastitis, abscess.',
        'Post breast reconstruction follow-up.',
        'Breast ultrasound and biopsy.',
        'Mammology consultation.',
    ],
    procto: [
        'Rectal bleeding — red, black or mixed.',
        'Anal pain — on defecation, sitting.',
        'Anal fissure — sharp pain, blood.',
        'Hemorrhoids — prolapse, pain, bleeding.',
        'Anal itching and discomfort.',
        'Bowel habit disorder — constipation or incontinence.',
        'Rectal prolapse — bowel protrusion.',
        'Perianal abscess — pain, fever, swelling.',
        'Colorectal screening — colonoscopy needed.',
        'Proctologic exam — rectal examination.',
        'Anal fistula — discharge, pain.',
        'Proctology consultation.',
    ],
    phthisio: [
        'Chronic cough — over 3 weeks.',
        'Night sweats, weight loss, anorexia.',
        'Subfebrile fever, fatigue — TB suspected.',
        'Dyspnea, chest pain — pleurisy.',
        'TB treated — surveillance, recurrence.',
        'TB contact — screening.',
        'Chest X-ray changes — infiltrate, cavity.',
        'Positive Mantoux or IGRA.',
        'Multidrug-resistant TB — difficult treatment.',
        'TB and HIV co-infection.',
        'Phthisiology follow-up — DOT therapy.',
        'Phthisiology consultation.',
    ],
    narcology: [
        'Alcohol dependence — unable to stop drinking.',
        'Alcohol withdrawal — tremor, sweating, aggression.',
        'Substance use — opioid, cannabinoid, stimulant.',
        'Detoxification needed — safe withdrawal.',
        'Rehabilitation — relapse prevention.',
        'Naltrexone or methadone therapy.',
        'Overdose — naloxone needed.',
        'Family history of addiction.',
        'Work or family problems — substance related.',
        'Dual diagnosis — psychiatric and addiction.',
        'Nicotine dependence — smoking cessation.',
        'Addiction follow-up.',
        'Positive drug test — work or legal.',
        'Narcology consultation.',
    ],
    rehab: [
        'Post stroke — paralysis, difficulty walking, speech disorder.',
        'Post surgery — joint replacement, disc, ligament.',
        'Spinal injury — paraplegia.',
        'Post MI — cardiopulmonary rehabilitation.',
        'Dyspnea — pulmonary rehabilitation.',
        'Pain syndrome — back, neck, fibromyalgia.',
        'Sports injury — rehabilitation and return.',
        'Child developmental delay — motor, speech.',
        'Post amputation — prosthesis and adaptation.',
        'Parkinson — movement, balance.',
        'Physiotherapy and exercise planned.',
        'Rehabilitation consultation.',
    ],
    sport: [
        'Sports injury — ligament or muscle tear.',
        'Knee pain — ACL, meniscus, patellofemoral.',
        'Shoulder pain — rotator cuff, impingement.',
        'Stress fracture — foot or leg.',
        'Contusion or laceration — sports.',
        'Overtraining — fatigue, performance decline.',
        'Sudden cardiac death risk — sports medical exam.',
        'Doping control — positive test.',
        'Return to sport — post injury clearance.',
        'Hydration and heat stroke prevention.',
        'Sports medicine consultation.',
        'Athlete preventive check-up.',
    ],
    hepat: [
        'Jaundice — liver or biliary tract.',
        'Right upper quadrant heaviness — hepatitis, steatosis.',
        'Viral hepatitis — HBV, HCV history.',
        'Alcoholic liver disease — elevated AST/ALT.',
        'Cirrhosis — ascites, varices, encephalopathy.',
        'Liver tumor suspected — AFP, CT.',
        'Autoimmune hepatitis — ANA, elevated IgG.',
        'Liver transplant listing or post-transplant.',
        'NASH/MAFLD — metabolic syndrome, overweight.',
        'Wilson disease — young, neurological signs.',
        'Hepatology workup — FibroScan, biopsy.',
        'Antiviral therapy — HCV treatment.',
        'Portal hypertension — bleeding, splenomegaly.',
        'Hepatology consultation.',
    ],
};

export const EN_FALLBACK_HISTORY_TEMPLATES: Partial<Record<SpecialtyKey, string[]>> = {
    surgeon: [
        'Prior abdominal surgery (appendectomy, cholecystectomy, etc.).',
        'Family history colorectal cancer or polyposis.',
        'On anticoagulants or antiplatelets — stop before surgery.',
        'Diabetes, heart disease — high perioperative risk.',
        'Prior general anesthesia, no complications.',
        'Long-term NSAIDs or analgesics.',
        'Smoking or alcohol — increases surgical risk.',
        'Prior hernia surgery, recurrence suspected.',
        'Oncology history — prior resection or chemotherapy.',
        'Preoperative workup — blood, ECG, X-ray done.',
    ],
    neurosurg: [
        'Prior brain or spinal surgery.',
        'VP shunt in place, on follow-up.',
        'Traumatic brain injury history.',
        'Family aneurysm or brain tumor.',
        'Anticoagulants — important before surgery.',
        'Epilepsy — medication regimen, surgery planned.',
        'Prior radiotherapy to brain.',
        'Preoperative MRI/CT done.',
    ],
    cardiosurg: [
        'Coronary artery disease — stent or bypass history.',
        'Valvular disease — echo shows stenosis or regurgitation.',
        'Aortic aneurysm surveillance — CT angiography.',
        'Family heart disease, early MI.',
        'Diabetes, hypertension — perioperative risk.',
        'Prior open heart surgery.',
        'Anticoagulants — with valve prosthesis.',
        'Preoperative cardiothoracic workup done.',
    ],
    vascular: [
        'Peripheral arterial disease — claudication.',
        'DVT or PE history — anticoagulants.',
        'Diabetes — foot ulcers, microangiopathy.',
        'Smoking — increases PAD risk.',
        'Varicose veins — prior surgery or sclerotherapy.',
        'Carotid stenosis — stroke risk.',
        'Endovascular or open surgery history.',
    ],
    plastic: [
        'Prior plastic or reconstructive surgery.',
        'Burn or trauma history.',
        'Keloid or hypertrophic scar formation.',
        'Oncology — post mastectomy reconstruction.',
        'Allergy — anesthetic or material.',
        'Preoperative plastic surgery consult done.',
    ],
    maxillofacial: [
        'Prior jaw or facial surgery.',
        'Tooth extraction or implant history.',
        'Trauma — facial fracture.',
        'TMJ disorder — prior treatment.',
        'Radiotherapy to head and neck.',
        'Preoperative maxillofacial workup.',
    ],
    onco: [
        'Prior cancer diagnosis — treatment and stage.',
        'Chemotherapy, radiotherapy or immunotherapy courses.',
        'Family cancer (breast, colorectal, prostate, etc.).',
        'Metastasis suspected — PET-CT planned.',
        'Palliative care — pain control.',
        'Tumor markers on surveillance.',
        'Remission — surveillance tests.',
        'Second opinion or treatment plan change.',
        'Supportive care — anemia, neutropenia.',
        'Full oncologic history documented.',
    ],
    pedia: [
        'Birth history — premature, asphyxia, APGAR.',
        'Immunization schedule — complete or delayed.',
        'Growth and development — weight, height, motor.',
        'Family allergy, asthma or cancer.',
        'Breast or formula feeding.',
        'Chronic disease in child — diabetes, epilepsy.',
        'Pediatric surgery or hospitalization.',
        'School or daycare — behavior, learning.',
        'Full pediatric history.',
        'Parent complaint and follow-up history.',
    ],
    neonat: [
        'Birth — gestational age, weight, APGAR.',
        'NICU stay — RDS, sepsis, jaundice.',
        'Maternal conditions — GDM, preeclampsia, infection.',
        'Neonatal surgery or malformation.',
        'Feeding — breast or formula.',
        'Neonatal screening — metabolic, hearing.',
        'Discharge follow-up — weight, jaundice.',
        'Neonatal history.',
    ],
    hemat: [
        'Prior transfusion or transplant.',
        'Family hematologic disease — thalassemia, hemophilia.',
        'Chemotherapy or radiotherapy.',
        'Anticoagulants or antiplatelets.',
        'Splenectomy done.',
        'Hematology workup — blood, marrow.',
        'Hematologic history.',
    ],
    infect: [
        'Travel history — tropical region, endemic zone.',
        'HIV or immunodeficiency.',
        'TB contact or prior TB treatment.',
        'Antibiotics used — name, duration.',
        'Animal contact — zoonosis risk.',
        'Vaccinations — hepatitis, flu, COVID.',
        'Infectious disease history.',
        'Prophylactic antibiotic or prevention.',
    ],
    emergency: [
        'Ambulance called — time and condition.',
        'Allergies — drug, food, anaphylaxis.',
        'Chronic diseases — heart, diabetes, epilepsy.',
        'Current medications — anticoagulant, insulin.',
        'Trauma mechanism — height, MVA, assault.',
        'Acute onset — when started.',
        'Emergency history — quickly gathered.',
        'Contact information — relative.',
    ],
    radiology: [
        'Prior X-ray, CT or MRI.',
        'Contrast allergy — iodine, gadolinium.',
        'Order reason — complaint, diagnosis suspicion.',
        'Pregnancy — radiation risk.',
        'Radiology history.',
    ],
    allergy: [
        'Family allergy, asthma, atopic dermatitis.',
        'Seasonal or perennial allergy.',
        'Food or drug allergy history.',
        'Anaphylaxis episode — when, cause.',
        'Immunotherapy course.',
        'Allergic history.',
    ],
    geriatr: [
        'Polypharmacy — 5+ drug list.',
        'Fall history — hip, arm fracture.',
        'Dementia or cognitive decline suspected.',
        'Living alone, social support.',
        'Functional status — walking, eating, hygiene.',
        'Family dementia or longevity.',
        'Geriatric history — comprehensive.',
        'Palliative or hospice plan.',
    ],
    dentistry: [
        'Prior dental treatment or surgery.',
        'Prosthesis, implant or orthodontics.',
        'Oral hygiene — regular cleaning.',
        'Tooth extraction history.',
        'Dental history.',
        'Child teething and feeding.',
    ],
    mammo: [
        'Family breast or ovarian cancer.',
        'Prior mammography or biopsy.',
        'Hormonal therapy — OCP, HRT.',
        'Pregnancy and lactation history.',
        'Breast surgery history.',
        'Mammologic history.',
    ],
    procto: [
        'Prior hemorrhoid or anal surgery.',
        'Colorectal screening — colonoscopy.',
        'Constipation or bowel habits.',
        'Family colorectal cancer.',
        'Proctologic history.',
    ],
    phthisio: [
        'TB contact — family or workplace.',
        'Prior TB treatment — DOT, duration.',
        'HIV or immunodeficiency.',
        'Prior positive Mantoux or IGRA.',
        'Smoking — increases TB risk.',
        'Phthisiology history.',
    ],
    narcology: [
        'Alcohol or substance use duration.',
        'Prior detox or rehabilitation.',
        'Family addiction.',
        'Psychiatric comorbidity.',
        'Work or legal problems.',
        'Addiction history.',
        'Drug test history.',
        'Nicotine dependence.',
    ],
    rehab: [
        'Stroke, trauma or surgery date.',
        'Rehabilitation course started or completed.',
        'Functional status — ADL, walking distance.',
        'Pain scale and limited movement.',
        'Rehabilitation history.',
        'Home or inpatient physiotherapy.',
    ],
    sport: [
        'Sport type and load.',
        'Prior sports injury and treatment.',
        'Doping test or rule compliance.',
        'Sports medical exam — heart, ECG.',
        'Sports history.',
        'Return to sport clearance.',
    ],
    hepat: [
        'Viral hepatitis — HBV, HCV, treatment.',
        'Alcohol use — amount, duration.',
        'Liver disease — cirrhosis, steatosis.',
        'Liver transplant listing.',
        'Family liver disease.',
        'Antiviral therapy.',
        'Hepatologic history.',
    ],
};

/** i18n kaliti topilmasa fallback qaytaradi */
export function resolveTemplate(
    t: (key: string) => string,
    key: string,
    fallback: string,
): string {
    const val = t(key);
    return val === key || !val ? fallback : val;
}

export function getComplaintTemplates(
    t: (key: string) => string,
    language?: string,
): Record<SpecialtyKey, string[]> {
    const useEn = language === 'en' || language === 'ru';
    const result = {} as Record<SpecialtyKey, string[]>;
    for (const key of SPECIALTY_ORDER) {
        const { complaintCount } = SPECIALTY_CONFIG[key];
        const fallbacks = useEn
            ? (EN_FALLBACK_COMPLAINT_TEMPLATES[key] ?? FALLBACK_COMPLAINT_TEMPLATES[key] ?? [])
            : (FALLBACK_COMPLAINT_TEMPLATES[key] ?? []);
        result[key] = Array.from({ length: complaintCount }, (_, i) =>
            resolveTemplate(t, `tmpl_${key}_comp_${i}`, fallbacks[i] ?? ''),
        ).filter(Boolean);
    }
    return result;
}

export function getHistoryTemplates(
    t: (key: string) => string,
    language?: string,
): Record<SpecialtyKey, string[]> {
    const useEn = language === 'en' || language === 'ru';
    const result = {} as Record<SpecialtyKey, string[]>;
    for (const key of SPECIALTY_ORDER) {
        const { historyCount } = SPECIALTY_CONFIG[key];
        const fallbacks = useEn
            ? (EN_FALLBACK_HISTORY_TEMPLATES[key] ?? FALLBACK_HISTORY_TEMPLATES[key] ?? [])
            : (FALLBACK_HISTORY_TEMPLATES[key] ?? []);
        result[key] = Array.from({ length: historyCount }, (_, i) =>
            resolveTemplate(t, `tmpl_${key}_hist_${i}`, fallbacks[i] ?? ''),
        ).filter(Boolean);
    }
    return result;
}
