# Generated by Django 5.2.14 on 2026-09-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_id', models.CharField(max_length=255, verbose_name='Protokol ID')),
                ('patient_data_hash', models.CharField(max_length=64, verbose_name="Bemor ma'lumotlari xeshi")),
                ('protocol_details', models.JSONField(default=dict, verbose_name='Protokol tafsilotlari')),
                ('patient_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Bemor kesimi')),
                ('treatment_success', models.BooleanField(blank=True, null=True, verbose_name='Davolash muvaffaqiyati')),
                ('patient_satisfaction', models.IntegerField(blank=True, null=True, verbose_name='Bemor qoniqishi (1-10)')),
                ('complication_occurred', models.BooleanField(default=False, verbose_name='Asoratlar yuz bergan')),
                ('complication_details', models.TextField(blank=True, verbose_name='Asorat tafsilotlari')),
                ('recovery_time_days', models.IntegerField(blank=True, null=True, verbose_name='Tiklanish vaqti (kun)')),
                ('follow_up_required', models.BooleanField(default=True, verbose_name='Keyingi kuzatuv kerak')),
                ('effectiveness_score', models.FloatField(default=0.0, verbose_name='Samaradorlik balli')),
                ('safety_score', models.FloatField(default=0.0, verbose_name='Xavfsizlik balli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Protokol natijasi',
                'verbose_name_plural': 'Protokol natijalari',
                'indexes': [models.Index(fields=['protocol_id'], name='po_protocol_id_idx'), models.Index(fields=['treatment_success'], name='po_success_idx'), models.Index(fields=['effectiveness_score'], name='po_effectiveness_idx'), models.Index(fields=['created_at'], name='po_created_at_idx')],
            },
        ),
    ]
