"""AiShifokor — premium Django admin (Jazzmin) sozlamalari."""

JAZZMIN_SETTINGS = {
    "site_title": "AiShifokor",
    "site_header": "AiShifokor Boshqaruv Markazi",
    "site_brand": "AiShifokor",
    "site_logo": None,
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Tibbiy platforma boshqaruv paneliga xush kelibsiz",
    "copyright": "Farg'ona JSTI · AiShifokor",
    "search_model": ["accounts.User", "patients.Patient", "analyses.AnalysisRecord"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Asosiy sayt", "url": "https://aishifokor.uz", "new_window": True},
        {"name": "API holati", "url": "/health/", "new_window": True},
        {"model": "accounts.User"},
    ],
    "usermenu_links": [
        {"name": "Saytga qaytish", "url": "https://aishifokor.uz", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "accounts",
        "patients",
        "analyses",
        "auth",
    ],
    "custom_links": {
        "accounts": [
            {
                "name": "Faol sessiyalar",
                "url": "admin:accounts_activesession_changelist",
                "icon": "fas fa-mobile-alt",
            },
            {
                "name": "Kutilayotgan to'lovlar",
                "url": "admin:accounts_subscriptionpayment_changelist",
                "icon": "fas fa-receipt",
            },
        ],
        "patients": [
            {
                "name": "Barcha bemorlar",
                "url": "admin:patients_patient_changelist",
                "icon": "fas fa-user-injured",
            },
        ],
    },
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users-cog",
        "accounts": "fas fa-hospital-user",
        "accounts.user": "fas fa-user-md",
        "accounts.clinicgroup": "fas fa-clinic-medical",
        "accounts.subscriptionplan": "fas fa-tags",
        "accounts.subscriptionpayment": "fas fa-money-check-alt",
        "accounts.activesession": "fas fa-mobile-alt",
        "patients": "fas fa-procedures",
        "patients.patient": "fas fa-user-injured",
        "patients.patientattachment": "fas fa-paperclip",
        "analyses": "fas fa-microscope",
        "analyses.analysisrecord": "fas fa-file-medical-alt",
        "analyses.diagnosisfeedback": "fas fa-comment-medical",
        "analyses.imagingstudyrecord": "fas fa-x-ray",
        "analyses.analysisauditlog": "fas fa-history",
        "analyses.analysisusefulnessfeedback": "fas fa-thumbs-up",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "admin/css/aishifokor_admin.css",
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "accounts.user": "collapsible",
        "auth.user": "collapsible",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-teal",
    "accent": "accent-teal",
    "navbar": "navbar-dark navbar-teal",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-teal",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "flatly",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": True,
}
